"""The example's correctness references come from the owner's FullProf file."""

import json
import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[3]
CASE = ROOT / 'docs/user/cli/pd-xray-cwl_latp_scan-4f'


def after(lines, prefix):
    index = next(index for index, line in enumerate(lines) if line.startswith(prefix))
    return [float(value) for value in lines[index + 1].split()]


def test_latp_reference_quantities_are_fullprof_values_not_scan_regression_pins():
    lines = (CASE / 'fullprof/latp.pcr').read_text().splitlines()
    quantities = json.loads((CASE / 'expected.json').read_text())['quantities']
    cell = after(lines, '!     a ')
    broadening = after(lines, '!       U ')
    shape = after(lines, '!  Scale ')
    ti = next(line.split() for line in lines if line.startswith('Ti1 '))
    phosphorus = next(line.split() for line in lines if line.startswith('P1 '))
    li = next(line.split() for line in lines if line.startswith('Li1 '))
    expected = {
        'n_free': float(next(line.split()[0] for line in lines if '!Number of' in line)),
        'param.latp.cell_length_a.value': cell[0],
        'param.latp.cell_length_c.value': cell[2],
        'param.latp.Ti1.fract_z.value': float(ti[4]),
        'param.latp.P1.fract_x.value': float(phosphorus[2]),
        'param.broad_gauss_u.value': broadening[0],
        'param.broad_gauss_w.value': broadening[2],
        'param.mixing_eta_0.value': shape[1],
        'param.latp.Li1.adp_iso.value': float(li[5]),
    }
    assert {name for name, row in quantities.items() if row['kind'] == 'reference'} == set(
        expected
    ), (
        'The LATP example must declare exactly the independently '
        'sourced FullProf reference quantities'
    )
    for name, value in expected.items():
        assert quantities[name]['value'] == pytest.approx(value, rel=0, abs=1e-12), (
            'Each LATP reference value must be read from the owner '
            'FullProf fit rather than generated by the scan'
        )
    assert (
        quantities['reduced_chi_square']['kind']
        == quantities['iterations']['kind']
        == 'regression-pin'
    ), 'The scan result chi-square and iteration count must remain labelled regression pins'
    assert float(re.search(r'Bragg contrib\.\) =\s+([\d.]+)', lines[1]).group(1)) == 7.048, (
        'The committed independent FullProf fit must retain its reported chi-square'
    )
