"""Transcribe the independent YAP summary into a fitting-corpus vehicle."""

import argparse
import json
from pathlib import Path

import numpy as np

from tests.fixtures.multiphase import fullprof


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--corpus-root', type=Path, required=True)
    args = parser.parse_args()
    ref = fullprof.reference()
    home = args.corpus_root / 'yap-spodi-3k'
    project = home / 'project'
    (project / 'structures').mkdir(parents=True)
    (project / 'experiments').mkdir()
    for name, phase in ref['phases'].items():
        text = f'data_{name}\n_edi.schema_version 3\n'
        for key, (value, su) in zip(
            ('length_a', 'length_b', 'length_c', 'angle_alpha', 'angle_beta', 'angle_gamma'),
            phase['cell'],
            strict=True,
        ):
            free = su > 0 and not (name == 'Al2O3' and key == 'length_b')
            text += f'_cell.{key} {value}{"()" if free else ""}\n'
        text += f'_space_group.name_h_m "{"P b n m" if name == "YAlO3" else "R -3 c"}"\n'
        if name == 'Al2O3':
            text += '_space_group.coord_system_code h\n'
        text += 'loop_\n' + ''.join(
            f'_atom_site.{k}\n'
            for k in (
                'id',
                'type_symbol',
                'wyckoff_letter',
                'fract_x',
                'fract_y',
                'fract_z',
                'occupancy',
                'adp_iso',
                'adp_type',
            )
        )
        for site, fields in phase['sites'].items():
            coords = ' '.join(
                str(fields[k][0]) + ('()' if fields[k][1] else '')
                for k in ('fract_x', 'fract_y', 'fract_z')
            )
            symbol = 'O' if site.startswith('O') else ('Y' if site == 'Y' else 'Al')
            text += (
                f'{site} {symbol} {fullprof.SITES[name][site][0]} {coords} '
                f'1 {fields["adp_iso"][0]}() Biso\n'
            )
        (project / 'structures' / f'{name}.edi').write_text(text)
    text = """data_spodi
_edi.schema_version 3
_experiment_type.beam_mode "constant wavelength"
_scattering_source.neutron_scattering_length sears1992
_instrument.setup_wavelength 1.54816
_instrument.calib_twotheta_offset 0.0015()
_peak.type cwl-pseudo-voigt-berar-baldinozzi
_peak.broad_gauss_u 0.03889()
_peak.broad_gauss_v -0.04620()
_peak.broad_gauss_w 0.10586()
_peak.mixing_eta_0 0.13947()
_peak.mixing_eta_1 0
_peak.asym_beba_a0 0()
_peak.asym_beba_b0 0()
_peak.asym_beba_a1 0()
_peak.asym_beba_b1 0()
_peak.asym_beba_limit 160
_peak.cutoff_fwhm 20
loop_
_linked_structure.structure_id
_linked_structure.scale
"""
    text += ''.join(f'{name} {phase["scale"]}()\n' for name, phase in ref['phases'].items())
    text += (
        '\n_background.type line-segment\nloop_\n_background.id\n_background.p'
        'osition\n_background.intensity\n'
    )
    positions = []
    pcr = (fullprof.HOME / 'yap_3k.pcr').read_text()
    lines = pcr.split('!2Theta/TOF/E(Kev)')[1].split('! Excluded regions')[0].splitlines()[1:]
    positions = [
        float(line.split()[0]) for line in lines if line.strip() and not line.startswith('!')
    ]
    for i, position in enumerate(positions):
        value = ref['parameters'][f'background.{i + 1}'][0]
        text += f'{i + 1} {position} {value}()\n'
    text += (
        '\nloop_\n_excluded_region.id\n_excluded_region.start\n_excluded_regio'
        'n.end\n1 0 4\n2 153.95 180\n'
    )
    data = np.loadtxt(fullprof.HOME / 'yap_3k.dat')
    data = data[(data[:, 0] >= 2.3) & (data[:, 0] <= 151.95)]
    text += '\nloop_\n_data.two_theta\n_data.intensity_meas\n_data.intensity_meas_su\n'
    text += ''.join(f'{x:.17g} {y:.17g} {max(su, 1):.17g}\n' for x, y, su in data)
    (project / 'experiments/spodi.edi').write_text(text)
    (project / 'analysis').mkdir()
    (project / 'analysis/analysis.edi').write_text(
        '_edi.schema_version 3\n'
        '_minimizer.max_iterations 150\n'
        '_minimizer.chi_square_tolerance 1e-8\n'
    )
    (home / 'PROVENANCE.md').write_text(
        'Transcribed from the owner-supplied, re-fitted YAP FullProf summary.\n'
        'Reference artifacts: edi knowledge/fitting/fullprof/pd-neut-cwl_yap-spodi_3k.\n'
        'Occupancies are restored using the cctbx multiplicities, independently '
        'checked by the reference gate.\n'
        'The Npr5 Caglioti width and fitted constant eta follow FullProf directly; '
        'the slope is fixed at zero.\n'
        'The four asymmetry coefficients start at zero in the engine convention.\n'
        'No fit value in this vehicle is generated by edi or crysta.\n'
        + json.dumps(ref['digests'], sort_keys=True)
        + '\n'
    )
    (home / 'expected.json').write_text(
        json.dumps(
            {
                'schema': 1,
                'source': {
                    'engine': 'FullProf.2k 8.40',
                    'artifact': 'PROVENANCE.md',
                    'provenance': 'PROVENANCE.md',
                },
                'quantities': {
                    'n_free': {'value': 56, 'kind': 'reference', 'tol_abs': 0, 'tol_rel': None},
                    'rwp': {
                        'value': 0.0408,
                        'kind': 'reference',
                        'tol_abs': None,
                        'tol_rel': 0.05,
                    },
                },
            },
            indent=2,
        )
        + '\n'
    )


if __name__ == '__main__':
    main()
