"""T8: every named loop-member change closes its mutable escape.

The member/type inventory is transcribed from accepted T8, not generated by the
implementation. Each negative compile has its own legal same-member control.
"""

import shutil
import subprocess
import tempfile
from pathlib import Path

import pytest

from tests.fixtures.c34_t28_compiler import crysta_headers
from tests.fixtures.c34_t28_compiler import standard_headers as _standard_headers

standard_headers = _standard_headers

ROOT = Path(__file__).resolve().parents[3]
# owner, member, original type, declared replacement, preserved expressions
MEMBERS = [
    (
        'Parameter',
        'uncertainty',
        'std::optional<double>',
        'edi::detail::Written<std::optional<double>>',
        (
            'o.M = 0.031; if (o.M) { (void)o.M.value(); } (void)o.M.has_value(); '
            '(void)o.M.value_or(2.5); o.M.reset(); o.M.emplace(4.125);'
        ),
    ),
    (
        'Parameter',
        'start_value',
        'std::optional<double>',
        'edi::detail::Written<std::optional<double>>',
        (
            'o.M = 0.031; if (o.M) { (void)o.M.value(); } (void)o.M.has_value(); '
            '(void)o.M.value_or(2.5); o.M.reset(); o.M.emplace(4.125);'
        ),
    ),
    (
        'Parameter',
        'start_uncertainty',
        'std::optional<double>',
        'edi::detail::Written<std::optional<double>>',
        (
            'o.M = 0.031; if (o.M) { (void)o.M.value(); } (void)o.M.has_value(); '
            '(void)o.M.value_or(2.5); o.M.reset(); o.M.emplace(4.125);'
        ),
    ),
    (
        'Parameter',
        'free',
        'bool',
        'edi::detail::Written<bool>',
        'o.M = true; bool v = o.M; (void)v;',
    ),
    (
        'SequentialExtractRule',
        'required',
        'bool',
        'edi::detail::Written<bool>',
        'o.M = true; bool v = o.M; (void)v;',
    ),
    (
        'AtomSite',
        'wyckoff_letter',
        'std::string',
        'edi::detail::WrittenText',
        ('o.M = "Fe1"; const std::string& v = o.M; (void)v; (void)o.M.size(); (void)o.M.empty();'),
    ),
    (
        'SequentialExtractRule',
        'target',
        'std::string',
        'edi::detail::WrittenText',
        ('o.M = "Fe1"; const std::string& v = o.M; (void)v; (void)o.M.size(); (void)o.M.empty();'),
    ),
    (
        'SequentialExtractRule',
        'pattern',
        'std::string',
        'edi::detail::WrittenText',
        ('o.M = "Fe1"; const std::string& v = o.M; (void)v; (void)o.M.size(); (void)o.M.empty();'),
    ),
    (
        'LineSegment',
        'position',
        'double',
        'edi::detail::Written<double>',
        ('o.M = 3; o.M += 2; o.M -= 1; o.M *= 2; o.M /= 2; const double& v = o.M; (void)v;'),
    ),
    (
        'PrefOrient',
        'index_h',
        'int',
        'edi::detail::Written<int>',
        ('o.M = 3; o.M += 2; o.M -= 1; o.M *= 2; o.M /= 2; const int& v = o.M; (void)v;'),
    ),
    (
        'PrefOrient',
        'index_k',
        'int',
        'edi::detail::Written<int>',
        ('o.M = 3; o.M += 2; o.M -= 1; o.M *= 2; o.M /= 2; const int& v = o.M; (void)v;'),
    ),
    (
        'PrefOrient',
        'index_l',
        'int',
        'edi::detail::Written<int>',
        ('o.M = 3; o.M += 2; o.M -= 1; o.M *= 2; o.M /= 2; const int& v = o.M; (void)v;'),
    ),
    (
        'PdDataBase',
        'intensity_meas',
        'std::vector<double>',
        'edi::detail::Written<std::vector<double>>',
        (
            'o.M = std::vector<double>{2.5, 4.125}; const std::vector<double>& v = '
            'o.M; (void)v; (void)o.M.size(); (void)o.M.begin(); (void)o.M.at(0);'
        ),
    ),
    (
        'PdDataBase',
        'intensity_meas_su',
        'std::vector<double>',
        'edi::detail::Written<std::vector<double>>',
        (
            'o.M = std::vector<double>{2.5, 4.125}; const std::vector<double>& v = '
            'o.M; (void)v; (void)o.M.size(); (void)o.M.begin(); (void)o.M.at(0);'
        ),
    ),
    (
        'PdDataBase',
        'two_theta',
        'std::optional<std::vector<double>>',
        'edi::detail::Written<std::optional<std::vector<double>>>',
        (
            'o.M = std::vector<double>{2.5, 4.125}; if (o.M) { const '
            'std::vector<double>& v = o.M.value(); (void)v; } o.M.reset(); '
            'o.M.emplace(std::vector<double>{1.25});'
        ),
    ),
    (
        'PdDataBase',
        'time_of_flight',
        'std::optional<std::vector<double>>',
        'edi::detail::Written<std::optional<std::vector<double>>>',
        (
            'o.M = std::vector<double>{2.5, 4.125}; if (o.M) { const '
            'std::vector<double>& v = o.M.value(); (void)v; } o.M.reset(); '
            'o.M.emplace(std::vector<double>{1.25});'
        ),
    ),
    (
        'Structure',
        'scattering_lengths_fm',
        'std::map<std::string, double>',
        'edi::detail::Written<std::map<std::string, double>>',
        (
            'o.M = std::map<std::string, double>{{"Fe", 9.45}}; const '
            'std::map<std::string, double>& v = o.M; (void)v; (void)o.M.find("Fe");'
            ' (void)o.M.count("Fe"); (void)o.M.at("Fe");'
        ),
    ),
    (
        'ExperimentBase',
        'excluded_regions',
        'std::vector<std::pair<double, double>>',
        'edi::detail::Written<std::vector<std::pair<double, double>>>',
        (
            'o.M = std::vector<std::pair<double, double>>{{1.25, 4.5}}; const '
            'std::vector<std::pair<double, double>>& v = o.M; (void)v; '
            '(void)o.M.front(); (void)o.M.back(); (void)o.M[0];'
        ),
    ),
    (
        'CarriedLoop',
        'columns',
        'std::vector<std::string>',
        'edi::detail::Written<std::vector<std::string>>',
        (
            'o.M = std::vector<std::string>{}; const std::vector<std::string>& v = '
            'o.M; (void)v; (void)o.M.begin(); (void)o.M.end(); (void)o.M.size(); '
            '(void)o.M.empty();'
        ),
    ),
    (
        'CarriedLoop',
        'rows',
        'std::vector<std::vector<std::string>>',
        'edi::detail::Written<std::vector<std::vector<std::string>>>',
        (
            'o.M = std::vector<std::vector<std::string>>{}; const '
            'std::vector<std::vector<std::string>>& v = o.M; (void)v; '
            '(void)o.M.begin(); (void)o.M.end(); (void)o.M.size(); '
            '(void)o.M.empty();'
        ),
    ),
]


def compile_probe(source, standard_headers):
    include_roots = [
        ROOT / 'core/include',
        crysta_headers(),
    ]
    command = [
        shutil.which('clang++'),
        '-std=c++20',
        '-fsyntax-only',
        '-include-pch',
        str(standard_headers),
        '-x',
        'c++',
    ]
    for directory in include_roots:
        command.extend(['-I', str(directory)])
    # A named translation unit keeps the actual member expression in GCC's
    # diagnostic, rather than accepting an unrelated failure from stdin.
    with tempfile.TemporaryDirectory(prefix='c34-edi-member-') as temporary:
        unit = Path(temporary) / 'probe.cpp'
        unit.write_text(source)
        return subprocess.run(
            [*command, str(unit)],
            cwd=ROOT,
            text=True,
            capture_output=True,
            check=False,
            timeout=25,
        )


def source(owner, body):
    return (
        '#include "edi/model.hpp"\n#include "crysta/column.hpp"\n'
        '#include <type_traits>\n#include <utility>\n'
        f'void probe(edi::{owner}& o) {{ {body} }}\n'
    )


@pytest.mark.parametrize(
    ('owner', 'member', '_old', 'new', 'kept'), MEMBERS, ids=[f'{r[0]}-{r[1]}' for r in MEMBERS]
)
def test_retyped_member_keeps_declared_reads_and_writes(
    owner, member, _old, new, kept, standard_headers
):
    body = (
        f'static_assert(std::is_same_v<decltype(&edi::{owner}::{member}), '
        f'{new} edi::{owner}::*>, " T8 exact declared member type"); ' + kept.replace('M', member)
    )
    result = compile_probe(source(owner, body), standard_headers)
    assert result.returncode == 0, (
        ' I20/T8 every named replacement must preserve its declared read/write forms: '
        + result.stderr
    )


ESCAPES = []
for _owner, _member, _old, _new, _kept in MEMBERS:
    ESCAPES.extend([
        (_owner, _member, 'reference', f'{_old}& escape = o.{_member};'),
        (_owner, _member, 'pointer', f'{_old}* escape = &o.{_member};'),
        (
            _owner,
            _member,
            'member-pointer',
            f'{_old} edi::{_owner}::* escape = &edi::{_owner}::{_member};',
        ),
    ])
    if _old.startswith('std::optional<double>'):
        ESCAPES.append((_owner, _member, 'optional-write', f'*o.{_member} = 2.5;'))
    elif _old.startswith('std::optional<'):
        ESCAPES.append((_owner, _member, 'optional-write', f'o.{_member}->push_back(2.5);'))
    elif _old.startswith(('std::vector<', 'std::map<')):
        ESCAPES.append((_owner, _member, 'in-place-clear', f'o.{_member}.clear();'))
    elif _old == 'std::string':
        ESCAPES.append((_owner, _member, 'in-place-character', f"o.{_member}[0] = 'X';"))


@pytest.mark.parametrize(
    ('owner', 'member', 'route', 'expression'),
    ESCAPES,
    ids=[f'{r[0]}-{r[1]}-{r[2]}' for r in ESCAPES],
)
def test_no_mutable_reference_can_escape_a_retyped_member(
    owner, member, route, expression, standard_headers
):
    control = compile_probe(source(owner, f'(void)o.{member};'), standard_headers)
    assert control.returncode == 0, (
        ' T8 a negative compilation requires the same actual member to resolve: ' + control.stderr
    )
    result = compile_probe(source(owner, expression), standard_headers)
    assert result.returncode != 0, (
        ' I14/T8 the actual native expression must refuse the mutable escape: '
        + owner
        + '::'
        + member
        + ' '
        + route
    )
    assert member in result.stderr, (
        ' T8 the compile refusal must identify the member reached by the escape'
    )


def test_measured_write_doors_keep_vector_values_with_new_member_pointer_types(standard_headers):
    body = """
using Column = edi::detail::Written<std::vector<double>>;
using Axis = edi::detail::Written<std::optional<std::vector<double>>>;
using D = edi::PdDataBase;
static_assert(std::is_same_v<decltype(&D::write_column),
    void (D::*)(Column D::*, std::vector<double>)>, " T8 column write signature");
static_assert(std::is_same_v<decltype(&D::write_axis),
    void (D::*)(Axis D::*, std::optional<std::vector<double>>)>,
    " T8 axis write signature");
o.write_column(&D::intensity_meas, {2.5, 4.125});
o.write_axis(&D::time_of_flight, std::vector<double>{2100.5, 3300.75});
"""
    result = compile_probe(source('PdDataBase', body), standard_headers)
    assert result.returncode == 0, (
        ' T8 measured write doors take the new member types and keep plain vector values: '
        + result.stderr
    )
