"""Behavioral controls for the  CIF and ProjectMetadata counterparts."""

from __future__ import annotations

import datetime
from pathlib import Path

import edi
import pytest

ROOT = Path(__file__).resolve().parents[3]
PROJECT = ROOT / 'tests/fixtures/e02_t2_ncaf_5bank/project'

# Frozen from diffraction-lib 0ffba46f's experiment descriptors.  The tags are its CIF
# vocabulary, not the products' dot-form .edi vocabulary; the non-default values are copied from
# the upstream CIF round-trip reference rather than generated by either parser under test.
REFERENCE_EXPERIMENT_CIF = """data_reference_cwl
_easydiffraction_experiment_type.sample_form powder
_easydiffraction_experiment_type.beam_mode 'constant wavelength'
_easydiffraction_experiment_type.radiation_probe neutron
_easydiffraction_experiment_type.scattering_type bragg
_diffrn_radiation_wavelength.value 1.494
_pd_calib.2theta_offset 0.6225
_easydiffraction_peak.broad_gauss_u 0.0834
_easydiffraction_peak.broad_gauss_v -0.1168
_easydiffraction_peak.broad_gauss_w 0.123
"""


@pytest.mark.parametrize('method_name', ['from_cif_str', 'from_cif_path'])
def test_c11_t48_experiment_cif_factories_parse_reference_values(
    tmp_path: Path,
    method_name: str,
) -> None:
    path = tmp_path / 'reference-experiment.cif'
    path.write_text(REFERENCE_EXPERIMENT_CIF, encoding='utf-8')
    source = REFERENCE_EXPERIMENT_CIF if method_name == 'from_cif_str' else path
    experiment = getattr(edi.ExperimentFactory, method_name)(source)

    assert experiment.name == 'reference_cwl', (
        'the experiment name must come from the real CIF data-block name'
    )
    assert float(experiment.instrument.setup_wavelength.value) == pytest.approx(
        1.494, abs=1.0e-12
    ), 'the wavelength must come from the frozen diffraction-lib CIF reference'
    assert float(experiment.instrument.calib_twotheta_offset.value) == pytest.approx(
        0.6225, abs=1.0e-12
    ), 'the two-theta offset must come from the frozen diffraction-lib CIF reference'
    for member, expected in {
        'broad_gauss_u': 0.0834,
        'broad_gauss_v': -0.1168,
        'broad_gauss_w': 0.123,
    }.items():
        assert float(getattr(experiment.peak, member).value) == pytest.approx(
            expected, abs=1.0e-12
        ), ('the peak value must come from the frozen diffraction-lib CIF reference', member)


def test_c11_t48_project_metadata_timestamps_are_utc_datetimes() -> None:
    metadata = edi.ProjectMetadata()
    for member in ('created', 'last_modified'):
        value = getattr(metadata, member)
        assert isinstance(value, datetime.datetime), (
            'ProjectMetadata timestamps must expose counterpart datetime values, not STAR strings',
            member,
        )
        assert value.tzinfo is datetime.UTC, (
            'ProjectMetadata timestamps must be explicitly UTC-aware',
            member,
        )
