#pragma once
#include <memory>
#include <iomanip>
#include <sstream>
#include <string>
#include <filesystem>
#include <fstream>
#include "edi/io.hpp"
#include "edi/model.hpp"

//  M1. Input only, never a golden generated by the function under test.
namespace e04_t10_fixture {
inline constexpr const char* t1 = "docs/user/cli/pd-neut-tof_ncaf-wish-2bank_start-3/project";
inline std::string calculation_text(const std::string& structure) {
    return "data_geometry_grid\n_edi.schema_version 2\n"
           "_experiment_type.sample_form powder\n"
           "_experiment_type.beam_mode \"constant wavelength\"\n"
           "_experiment_type.radiation_probe neutron\n"
           "_experiment_type.scattering_type bragg\n_calculator.type crysta\n"
           "_peak.type cwl-tch-pseudo-voigt\n_peak.broad_gauss_u 0\n"
           "_peak.broad_gauss_v 0\n_peak.broad_gauss_w 0.1\n"
           "_peak.broad_lorentz_x 0\n_peak.broad_lorentz_y 0\n_peak.cutoff_fwhm 12\n"
           "_instrument.setup_wavelength 1.54\n_instrument.calib_twotheta_offset 0\n"
           "loop_\n_linked_structure.structure_id\n_linked_structure.scale\n" +
           structure + " 1\n_data_range.two_theta_min 10\n"
           "_data_range.two_theta_max 12\n_data_range.two_theta_step 1\n";
}
// Visible input generator. The CIF writer refuses to persist a calculation grid
// as observations; use it for the structure/metadata, then declare the input grid.
inline void write_calculation_project(const edi::Project& input,const std::string& directory) {
    auto structure_only=input;structure_only.experiments.clear();
    edi::save_project(structure_only,directory);
    std::filesystem::create_directories(std::filesystem::path(directory)/"experiments");
    std::ofstream file(std::filesystem::path(directory)/"experiments/geometry_grid.edi");
    file.exceptions(std::ios::failbit | std::ios::badbit);
    file << calculation_text(input.structure().name);
}
inline std::string generated_text() {
    std::ostringstream text;
    text << std::setprecision(17) << "data_G1\n_edi.schema_version 2\n"
         << "_cell.length_a 30\n_cell.length_b 30\n_cell.length_c 30\n"
         << "_cell.angle_alpha 90\n_cell.angle_beta 90\n_cell.angle_gamma 90\n"
         << "_space_group.name_h_m \"F m -3 m\"\n"
         << "_geom.min_bond_distance_cutoff 0\n_geom.bond_distance_inc 0.25\n"
         << "loop_\n_atom_site.id\n_atom_site.type_symbol\n_atom_site.fract_x\n"
         << "_atom_site.fract_y\n_atom_site.fract_z\n_atom_site.wyckoff_letter\n_atom_site.occupancy\n"
         << "_atom_site.adp_iso\n_atom_site.adp_type\n";
    for(int i=0;i<30;++i) {
        const std::string symbol=i%3==0?"Fe":i%3==1?"O":"La";
        text << symbol << i+1 << ' ' << symbol << ' ' << .011+.0157*i << ' '
             << .073+.0131*i << ' ' << .127+.0113*i << " l 1 0.5 Biso\n";
    }
    return text.str();
}
inline edi::Project generated() {
    edi::Project project;
    project.structures.clear();
    project.experiments.clear();
    edi::Structure s;
    s.name = "G1";
    s.space_group.name_h_m = "F m -3 m";
    s.cell.length_a.value = 30;
    s.cell.length_b.value = 30;
    s.cell.length_c.value = 30;
    for (int i = 0; i != 30; ++i) {
        auto site = std::make_shared<edi::AtomSite>();
        site->type_symbol = i % 3 == 0 ? "Fe" : i % 3 == 1 ? "O" : "La";
        site->id = site->type_symbol + std::to_string(i + 1);
        site->fract_x.value = .011 + .0157 * i;
        site->fract_y.value = .073 + .0131 * i;
        site->fract_z.value = .127 + .0113 * i;
        site->wyckoff_letter = "l";  // F m -3 m general position, multiplicity 192.
        site->occupancy.value = 1;
        site->adp_type = "Biso";
        site->adp_iso.value = .5;
        s.atom_sites.push_back(site);
    }
    project.structures.push_back(s);
    project.experiments.push_back(edi::experiment_from_edi_text(calculation_text("G1")));
    return project;
}
}  // namespace e04_t10_fixture
