// Generated by generate_display.py; .edi + ITA identities, never app output.
var frozen = {
  "sources": {
    "docs/user/cli/pd-neut-cwl_cosio-d20_start-1/project/structures/cosio.edi": "7ec9ca0fb52e1c29aa6a5aa68ca0e6a58db75ccc369a613f32d2036221994b48",
    "docs/user/cli/pd-neut-cwl_cosio-d20_start-1/project/experiments/d20.edi": "c0ef1ce128acbcc94eda9294f6afd63fd80c059eb7f7e5f1c5981f3efb07fbca",
    "docs/user/cli/pd-neut-cwl_cosio-d20_start-1/project/analysis/analysis.edi": "06acc049b2fdfd16e06af5c03634f364d62a2819d2bb2b0ea456cd4b79ba5061",
    "docs/user/cli/pd-neut-cwl_cosio-d20_start-4/project/structures/cosio.edi": "7ec9ca0fb52e1c29aa6a5aa68ca0e6a58db75ccc369a613f32d2036221994b48",
    "docs/user/cli/pd-neut-cwl_cosio-d20_start-4/project/experiments/d20.edi": "6b86e5db73f55ae128b14d5ab237595530483f4543886f7e8d4012d30e05e1be",
    "docs/user/cli/pd-neut-cwl_cosio-d20_start-4/project/analysis/analysis.edi": "06acc049b2fdfd16e06af5c03634f364d62a2819d2bb2b0ea456cd4b79ba5061",
    "docs/user/cli/pd-neut-cwl_cosio-d20_scan-3f/project/structures/cosio.edi": "1b3afde2d3a8184d6cb9789fa3fc8fa5dd026756a51e44a2cca6b80b9df8103a",
    "docs/user/cli/pd-neut-cwl_cosio-d20_scan-3f/project/experiments/d20.edi": "0c97d871957341359beee76e7029f77d1bf0ed4eb8e4709733fe794fe3516a1c",
    "docs/user/cli/pd-neut-cwl_cosio-d20_scan-3f/project/analysis/analysis.edi": "fde9a40134aaf6794cde3e396a01067e1018d78871c394d4646c95052416f726",
    "docs/user/cli/pd-neut-cwl_cosio-d20_scan-324f/project/structures/cosio.edi": "4538c66b979d5783c2c3b5ba8c06494a54efeea3fc83c5488e89d5a10c0bb899",
    "docs/user/cli/pd-neut-cwl_cosio-d20_scan-324f/project/experiments/d20.edi": "53ba4c8c28755334c633f23040fa411149d66294dc102862918ff461b09eca73",
    "docs/user/cli/pd-neut-cwl_cosio-d20_scan-324f/project/analysis/analysis.edi": "b732d6abb6017d11a7f25d30349975e45b2ba72a25cf13f8c702376ea4d6bbf9",
    "docs/user/cli/pd-neut-cwl_lbco-hrpt_start-2/project/structures/lbco.edi": "1c8421e95c44cad8dce012f78e57ed2bcabd783c76443eddf0d5d16873cba5c3",
    "docs/user/cli/pd-neut-cwl_lbco-hrpt_start-2/project/experiments/hrpt.edi": "5063e9ea674694f4ba201a2b7f77b985ae7a8c74111091912f6f9999e15ee2df",
    "docs/user/cli/pd-neut-cwl_lbco-hrpt_start-2/project/analysis/analysis.edi": "06acc049b2fdfd16e06af5c03634f364d62a2819d2bb2b0ea456cd4b79ba5061",
    "docs/user/cli/pd-neut-cwl_lbco-hrpt_start-4/project/structures/lbco.edi": "1c8421e95c44cad8dce012f78e57ed2bcabd783c76443eddf0d5d16873cba5c3",
    "docs/user/cli/pd-neut-cwl_lbco-hrpt_start-4/project/experiments/hrpt.edi": "c7a093e4cdee2aeca6553b84cca81293b748caeb6270d2083b5a043724128c26",
    "docs/user/cli/pd-neut-cwl_lbco-hrpt_start-4/project/analysis/analysis.edi": "06acc049b2fdfd16e06af5c03634f364d62a2819d2bb2b0ea456cd4b79ba5061",
    "docs/user/cli/pd-neut-tof_ncaf-wish-2bank_start-3/project/structures/ncaf.edi": "f61f4922cf075908b47b4fd3b14c32f7aefef8e339d6161a5fece184396f865b",
    "docs/user/cli/pd-neut-tof_ncaf-wish-2bank_start-3/project/experiments/wish_4_7.edi": "15a16d72f02eb93f4aa0eda13b5cfb77a05c2abcee6689821caba5b47f37636d",
    "docs/user/cli/pd-neut-tof_ncaf-wish-2bank_start-3/project/experiments/wish_5_6.edi": "936b75830a0eb724abc277846c574328b303f95568fa74b067bfc812b3224bfc",
    "docs/user/cli/pd-neut-tof_ncaf-wish-2bank_start-3/project/analysis/analysis.edi": "362967ebcac29cd81a538ba27f01b70d61eb04bfcbf8d2de0ba4e13bb271e428",
    "docs/user/cli/pd-neut-tof_ncaf-wish-3bank_start-5/project/structures/ncaf.edi": "1f231ef2dc1ec210d95b9f52452dacb6102b7c515b6af603f205199a3aaf0e1d",
    "docs/user/cli/pd-neut-tof_ncaf-wish-3bank_start-5/project/experiments/wish_2_9.edi": "761e2bed99259c0c0e679bdbfa5455671422ea953774f5450ba3edff6bd2200b",
    "docs/user/cli/pd-neut-tof_ncaf-wish-3bank_start-5/project/experiments/wish_4_7.edi": "e63425979da16bed1c0cb0061700d1855a5847fb48e5ce0477bf293284cf204e",
    "docs/user/cli/pd-neut-tof_ncaf-wish-3bank_start-5/project/experiments/wish_5_6.edi": "bb48d4b9c197737a2d35ef406dd3257bbe20dde70a6907bec5d14c8fd2e591a1",
    "docs/user/cli/pd-neut-tof_ncaf-wish-3bank_start-5/project/analysis/analysis.edi": "bc78689c1a4491d308a0611490dceed83edb4898244ae092ec555ee91a548484",
    "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-5/project/structures/ncaf.edi": "1f231ef2dc1ec210d95b9f52452dacb6102b7c515b6af603f205199a3aaf0e1d",
    "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-5/project/experiments/wish_1_10.edi": "6893edefb924126beb3817b349dc4f263ff11308172d7cfff70dd9b003b6b67c",
    "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-5/project/experiments/wish_2_9.edi": "cf1953881302612f1dd7f659ac76026c2f75dfd929f6a846b7c0c822328eef19",
    "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-5/project/experiments/wish_3_8.edi": "58437073a03edf8861f09c22d0ddc85637268b35e189f76dc430b62068af0bfa",
    "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-5/project/experiments/wish_4_7.edi": "5642c0c37de594406461d2b66ef20d09c46e4cd3af26d1f92e4615714179a6ae",
    "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-5/project/experiments/wish_5_6.edi": "555792faa1e574fad3b12a810b6aa7dc67abad14977453c97d65a9d0b8826b3b",
    "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-5/project/analysis/analysis.edi": "39fbca0c5cfba66ab4e126f6070c173209bdec5b984a7462a84e702363e3570f",
    "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-fullprof/project/structures/ncaf.edi": "44fe96e2d76e9a75815b831c6d060773e6129c8589aa5da5cd7e5b9e6b853eee",
    "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-fullprof/project/experiments/wish_1_10.edi": "1daf13e94e0fde89c44822d226109b527c2bde097c33b8f20465d6e83ba7b1d5",
    "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-fullprof/project/experiments/wish_2_9.edi": "7258aadc1cef7d305d237f7c5e031ee27251f0756159b61ad726cb24bfed435b",
    "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-fullprof/project/experiments/wish_3_8.edi": "947f6b21e94bdfcf541ef46896b7fed26b91512da0c54084b429b75e24dbc05c",
    "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-fullprof/project/experiments/wish_4_7.edi": "a0afd8a05804802f03de14361fb212c63a3549e61c6e32895fd83ee534312843",
    "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-fullprof/project/experiments/wish_5_6.edi": "bf45ed7b5f511d26c9d49adf0b13224a87d06245504d377dd5cfe4d4ffadaeb7",
    "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-fullprof/project/analysis/analysis.edi": "39fbca0c5cfba66ab4e126f6070c173209bdec5b984a7462a84e702363e3570f",
    "docs/user/cli/pd-neut-tof_si-sepd_start-2/project/structures/si.edi": "531d657005b89223d20b18265ace558c8fba96473890fb91a86e77dd80ca8f94",
    "docs/user/cli/pd-neut-tof_si-sepd_start-2/project/experiments/sepd.edi": "0b1167d3ccd41b2da642e443d5beb606932eea98580cd08364e21e51a4350152",
    "docs/user/cli/pd-neut-tof_si-sepd_start-2/project/analysis/analysis.edi": "9f58295877950335b95efa1716755b1247203d5be0475d9520960a0584d2b17f",
    "docs/user/cli/pd-neut-tof_si-sepd_start-5/project/structures/si.edi": "531d657005b89223d20b18265ace558c8fba96473890fb91a86e77dd80ca8f94",
    "docs/user/cli/pd-neut-tof_si-sepd_start-5/project/experiments/sepd.edi": "4e49721b5e31d508798e5ad56db99fa37ba83bfd324df051776713402deeffc0",
    "docs/user/cli/pd-neut-tof_si-sepd_start-5/project/analysis/analysis.edi": "9f58295877950335b95efa1716755b1247203d5be0475d9520960a0584d2b17f",
    "docs/user/cli/pd-neut-tof_diamond-dream_basic/project/structures/diamond.edi": "57650796c81a5963ee142a26847f89d9dac23cb6bc018406c77c6141a68f2613",
    "docs/user/cli/pd-neut-tof_diamond-dream_basic/project/experiments/dream.edi": "8fd1f452e2d02e32dddef6ef8cfedd101d954092f99a2e302b203d46868c0a9c",
    "docs/user/cli/pd-neut-tof_diamond-dream_basic/project/analysis/analysis.edi": "c859cfebc586252e3b1572cd54f854592d55a143b97302621120483df4733340",
    "docs/user/cli/pd-neut-cwl_lab6-echidna_fcj-asymmetry/project/structures/lab6.edi": "ae52d392119f81a94e77ba4128ee2afc447fbcd3bdd9cdc6e2fea56eba54074d",
    "docs/user/cli/pd-neut-cwl_lab6-echidna_fcj-asymmetry/project/experiments/echidna.edi": "133539d1a5bfb8611e3afbe487b7397f817aeb79e65376929ea4681cd91fdb2e",
    "docs/user/cli/pd-neut-cwl_lab6-echidna_fcj-asymmetry/project/analysis/analysis.edi": "622953d9f61a1927cfdde76b6296bf57805006e83817b80cd36f851b35d8ef79",
    "docs/user/cli/pd-neut-cwl_pbso4_beba-asymmetry/project/structures/pbso4.edi": "d14b19ea6dc7f6f3a129fa5fb3538f7413fc3cb727950c2f70fb9e2e6e3f2520",
    "docs/user/cli/pd-neut-cwl_pbso4_beba-asymmetry/project/experiments/d1a.edi": "f02575053ccb68d9047209eada95ef0042fc632ffdef67024c5bd1198d5a8ddb",
    "docs/user/cli/pd-neut-cwl_pbso4_beba-asymmetry/project/analysis/analysis.edi": "494db6eaa33dd5b4e18e6fc2d28282486b2d9bfc50a8e52098e6ad34422062fd",
    "docs/user/cli/pd-neut-cwl_yap-spodi_3k/project/structures/Al2O3.edi": "f5d727bf0362dae6abfb4c2503669e83085bc897cbb09db913b359eb37999472",
    "docs/user/cli/pd-neut-cwl_yap-spodi_3k/project/structures/YAlO3.edi": "7a4c6c27b6314bca5d179350c2ee75e1e27565a6c59629c17ed11662e29a2ccb",
    "docs/user/cli/pd-neut-cwl_yap-spodi_3k/project/experiments/spodi.edi": "f89b143912601bef9a62b3f61c6ff25c6988759785333e7186244c130b3d5e62",
    "docs/user/cli/pd-neut-cwl_yap-spodi_3k/project/analysis/analysis.edi": "77ef8e7ab8edb6b3f1addcde5a59c0c3b0f8e7cba8e0a4f116b30b4792210066",
    "docs/user/cli/pd-neut-tof_fe_pseudo-voigt/project/structures/fe.edi": "9ee23e6fff7c5eb544677380a5c3176ee7425e3e790cbe7b50dca77472a16c29",
    "docs/user/cli/pd-neut-tof_fe_pseudo-voigt/project/experiments/beer.edi": "21dcae63234608537b5d9f17a25e2d0554978df3f39d8476660a382e965739dd",
    "docs/user/cli/pd-neut-tof_fe_pseudo-voigt/project/analysis/analysis.edi": "7936851a579a0171a425595f5090909d327362a0da203615725f2f2ceacbf642",
    "docs/user/cli/pd-neut-tof_cecoal-polaris_chebyshev/project/structures/cecoal.edi": "f6939b1d7fe11a4b7e8451ec9a4acb468c21522ef4a29af3995b86758e910616",
    "docs/user/cli/pd-neut-tof_cecoal-polaris_chebyshev/project/experiments/polaris.edi": "afce3099188fcfab304513b8aaae8cf32cffc4f9c3177df8b7f3dbbd5b87adf0",
    "docs/user/cli/pd-neut-tof_cecoal-polaris_chebyshev/project/analysis/analysis.edi": "603772c6d4c286e53eb8554e6d2be4843c8f560cb942fec808bb8ca138eb993f",
    "docs/user/cli/pd-neut-tof_ceo2-pearl_polynomial/project/structures/ceo2.edi": "aedac6b487103b77e50f106e073b5701214efed16a787a9832391ce2c3b4b79c",
    "docs/user/cli/pd-neut-tof_ceo2-pearl_polynomial/project/experiments/pearl.edi": "a0ecad005d7d2b5729a2822b8cda98b8bfffae586361491dcbc5f8454ca69dd6",
    "docs/user/cli/pd-neut-tof_ceo2-pearl_polynomial/project/analysis/analysis.edi": "603772c6d4c286e53eb8554e6d2be4843c8f560cb942fec808bb8ca138eb993f",
    "docs/user/cli/pd-neut-cwl_lab6-11b-echidna_tch-fcj/project/structures/lab6.edi": "06d8ee9eadd4dd9c5f72aed4f264446172a15f81a0571e4a02adfba6156a53fd",
    "docs/user/cli/pd-neut-cwl_lab6-11b-echidna_tch-fcj/project/experiments/echidna.edi": "6c9fc1b2b342f03c4b15ed7fb41f6afe9f9029ec1b3f05eaa6348e526d70c72e",
    "docs/user/cli/pd-neut-cwl_lab6-11b-echidna_tch-fcj/project/analysis/analysis.edi": "603772c6d4c286e53eb8554e6d2be4843c8f560cb942fec808bb8ca138eb993f",
    "docs/user/cli/pd-xray-cwl_lif_single/project/structures/lif.edi": "b68e864053c85ea3bb0e7a14b37131c7319cd2cd047b89d4dc4d8b30ff4033fe",
    "docs/user/cli/pd-xray-cwl_lif_single/project/experiments/cu_ka.edi": "5be14a0525ce8a09124e9f1beaa52fc12f3b49d9bf8201f19b6ac2c68948de5b",
    "docs/user/cli/pd-xray-cwl_lif_single/project/analysis/analysis.edi": "76917b3672c7268e7fee9fb901c0ed8ffdd5ffcf29c6fc1083d470ad5b501e72",
    "docs/user/cli/pd-neut-tof_ferrite-austenite-beer_joint/project/structures/austenite.edi": "6b3eb1dab5b142687ed34263f04986ab3474bedfcaf9ce0d0ee7831f69929c93",
    "docs/user/cli/pd-neut-tof_ferrite-austenite-beer_joint/project/structures/ferrite.edi": "500fcf2007cefefb4b4477e10006596520d8e1cb8e61945d0791ff14ef27521c",
    "docs/user/cli/pd-neut-tof_ferrite-austenite-beer_joint/project/experiments/expt_n2.edi": "6e8f4ac836219d4ba503ff5583823b1d12eb523f788e16c03d86b2b5d2bacdda",
    "docs/user/cli/pd-neut-tof_ferrite-austenite-beer_joint/project/experiments/expt_s2.edi": "948b6f720ed6d72a5d5f0c5b8b06cae3dca6159f4f9e6edd56739110a2f2290a",
    "docs/user/cli/pd-neut-tof_ferrite-austenite-beer_joint/project/analysis/analysis.edi": "e228e179bbb95062d1646300ac68b92cbc0692d9b34a436ed944ef97cdd3df07",
    "tests/fixtures/e04_t1/xray-project/structures/structure.edi": "3eafe9649956cbc14b8f4be0f687089c0c7234f32ecd48232d75fe93c8d5a166",
    "tests/fixtures/e04_t1/xray-project/experiments/experiment.edi": "b7660875a00c409f028074f3421c47d057086b639980b1327759ece7b23ebb25",
    "tests/fixtures/e04_t1/xray-project/analysis/analysis.edi": "7515093456b82f2f2b413642dc503ce3cf723cf0951d25bc23ddddc26ddafcce",
    "tests/fixtures/e04_t1/editable-project/structures/lbco.edi": "7f69d050d5ba4d9e5a43e551377f8be5d71b487418c83645044cbec0c3c16af2",
    "tests/fixtures/e04_t1/editable-project/experiments/hrpt.edi": "5063e9ea674694f4ba201a2b7f77b985ae7a8c74111091912f6f9999e15ee2df",
    "tests/fixtures/e04_t1/editable-project/analysis/analysis.edi": "06acc049b2fdfd16e06af5c03634f364d62a2819d2bb2b0ea456cd4b79ba5061",
    "tests/fixtures/e04_t1/warning-project/structures/structure.edi": "3eafe9649956cbc14b8f4be0f687089c0c7234f32ecd48232d75fe93c8d5a166",
    "tests/fixtures/e04_t1/warning-project/experiments/experiment.edi": "b7660875a00c409f028074f3421c47d057086b639980b1327759ece7b23ebb25",
    "tests/fixtures/e04_t1/warning-project/analysis/analysis.edi": "33c098eabbed069d94371c84c54edd22ba57e04c41fd100032bde29f45e2e167"
  },
  "cases": [
    {
      "tag": "docs/user/cli/pd-neut-cwl_cosio-d20_start-1/project:space_group:cosio",
      "path": "docs/user/cli/pd-neut-cwl_cosio-d20_start-1/project",
      "page": "structure",
      "tier": "basic",
      "group": "space_group",
      "selection": "cosio",
      "fields": [
        [
          "spaceGroup.crystalSystem",
          "orthorhombic",
          "readonly"
        ],
        [
          "spaceGroup.itNumber",
          "62",
          "text"
        ],
        [
          "spaceGroup.nameHM",
          "P n m a",
          "text"
        ],
        [
          "spaceGroup.coordSystemCode",
          "abc",
          "text"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_cosio-d20_start-1/project:experiment_type:d20",
      "path": "docs/user/cli/pd-neut-cwl_cosio-d20_start-1/project",
      "page": "experiment",
      "tier": "basic",
      "group": "experiment_type",
      "selection": "d20",
      "fields": [
        [
          "experimentType.sampleForm",
          "powder",
          "disabled"
        ],
        [
          "experimentType.beamMode",
          "constant wavelength",
          "disabled"
        ],
        [
          "experimentType.radiationProbe",
          "neutron",
          "disabled"
        ],
        [
          "experimentType.scatteringType",
          "bragg",
          "disabled"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_cosio-d20_start-1/project:data:d20",
      "path": "docs/user/cli/pd-neut-cwl_cosio-d20_start-1/project",
      "page": "experiment",
      "tier": "extras",
      "group": "data",
      "selection": "d20",
      "fields": [
        [
          "range.minimum",
          8.0953,
          "number"
        ],
        [
          "range.maximum",
          150.0953,
          "number"
        ],
        [
          "range.step",
          "0.1\u20130.3",
          "readonly"
        ],
        [
          "range.points",
          1418,
          "number"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_cosio-d20_start-1/project:engines",
      "path": "docs/user/cli/pd-neut-cwl_cosio-d20_start-1/project",
      "page": "analysis",
      "tier": "extras",
      "group": "engines",
      "selection": null,
      "fields": [
        [
          "statusBar.calculator",
          "crysta",
          "label"
        ],
        [
          "statusBar.minimizer",
          "crysta",
          "label"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_cosio-d20_start-4/project:space_group:cosio",
      "path": "docs/user/cli/pd-neut-cwl_cosio-d20_start-4/project",
      "page": "structure",
      "tier": "basic",
      "group": "space_group",
      "selection": "cosio",
      "fields": [
        [
          "spaceGroup.crystalSystem",
          "orthorhombic",
          "readonly"
        ],
        [
          "spaceGroup.itNumber",
          "62",
          "text"
        ],
        [
          "spaceGroup.nameHM",
          "P n m a",
          "text"
        ],
        [
          "spaceGroup.coordSystemCode",
          "abc",
          "text"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_cosio-d20_start-4/project:experiment_type:d20",
      "path": "docs/user/cli/pd-neut-cwl_cosio-d20_start-4/project",
      "page": "experiment",
      "tier": "basic",
      "group": "experiment_type",
      "selection": "d20",
      "fields": [
        [
          "experimentType.sampleForm",
          "powder",
          "disabled"
        ],
        [
          "experimentType.beamMode",
          "constant wavelength",
          "disabled"
        ],
        [
          "experimentType.radiationProbe",
          "neutron",
          "disabled"
        ],
        [
          "experimentType.scatteringType",
          "bragg",
          "disabled"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_cosio-d20_start-4/project:data:d20",
      "path": "docs/user/cli/pd-neut-cwl_cosio-d20_start-4/project",
      "page": "experiment",
      "tier": "extras",
      "group": "data",
      "selection": "d20",
      "fields": [
        [
          "range.minimum",
          8.0953,
          "number"
        ],
        [
          "range.maximum",
          150.0953,
          "number"
        ],
        [
          "range.step",
          "0.1\u20130.3",
          "readonly"
        ],
        [
          "range.points",
          1418,
          "number"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_cosio-d20_start-4/project:engines",
      "path": "docs/user/cli/pd-neut-cwl_cosio-d20_start-4/project",
      "page": "analysis",
      "tier": "extras",
      "group": "engines",
      "selection": null,
      "fields": [
        [
          "statusBar.calculator",
          "crysta",
          "label"
        ],
        [
          "statusBar.minimizer",
          "crysta",
          "label"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_cosio-d20_scan-3f/project:space_group:cosio",
      "path": "docs/user/cli/pd-neut-cwl_cosio-d20_scan-3f/project",
      "page": "structure",
      "tier": "basic",
      "group": "space_group",
      "selection": "cosio",
      "fields": [
        [
          "spaceGroup.crystalSystem",
          "orthorhombic",
          "readonly"
        ],
        [
          "spaceGroup.itNumber",
          "62",
          "text"
        ],
        [
          "spaceGroup.nameHM",
          "P n m a",
          "text"
        ],
        [
          "spaceGroup.coordSystemCode",
          "abc",
          "text"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_cosio-d20_scan-3f/project:experiment_type:d20",
      "path": "docs/user/cli/pd-neut-cwl_cosio-d20_scan-3f/project",
      "page": "experiment",
      "tier": "basic",
      "group": "experiment_type",
      "selection": "d20",
      "fields": [
        [
          "experimentType.sampleForm",
          "powder",
          "disabled"
        ],
        [
          "experimentType.beamMode",
          "constant wavelength",
          "disabled"
        ],
        [
          "experimentType.radiationProbe",
          "neutron",
          "disabled"
        ],
        [
          "experimentType.scatteringType",
          "bragg",
          "disabled"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_cosio-d20_scan-3f/project:data:d20",
      "path": "docs/user/cli/pd-neut-cwl_cosio-d20_scan-3f/project",
      "page": "experiment",
      "tier": "extras",
      "group": "data",
      "selection": "d20",
      "fields": [
        [
          "range.minimum",
          0.0953,
          "number"
        ],
        [
          "range.maximum",
          150.8953,
          "number"
        ],
        [
          "range.step",
          "0.1\u20130.2",
          "readonly"
        ],
        [
          "range.points",
          1507,
          "number"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_cosio-d20_scan-3f/project:sequential_fit",
      "path": "docs/user/cli/pd-neut-cwl_cosio-d20_scan-3f/project",
      "page": "analysis",
      "tier": "extras",
      "group": "sequential_fit",
      "selection": null,
      "fields": [
        [
          "sequentialFit.dataDir",
          "experiments/d20_scan",
          "readonly"
        ],
        [
          "sequentialFit.filePattern",
          "*.dat",
          "readonly"
        ],
        [
          "sequentialFit.reverse",
          "false",
          "readonly"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_cosio-d20_scan-3f/project:engines",
      "path": "docs/user/cli/pd-neut-cwl_cosio-d20_scan-3f/project",
      "page": "analysis",
      "tier": "extras",
      "group": "engines",
      "selection": null,
      "fields": [
        [
          "statusBar.calculator",
          "crysta",
          "label"
        ],
        [
          "statusBar.minimizer",
          "crysta",
          "label"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_cosio-d20_scan-324f/project:space_group:cosio",
      "path": "docs/user/cli/pd-neut-cwl_cosio-d20_scan-324f/project",
      "page": "structure",
      "tier": "basic",
      "group": "space_group",
      "selection": "cosio",
      "fields": [
        [
          "spaceGroup.crystalSystem",
          "orthorhombic",
          "readonly"
        ],
        [
          "spaceGroup.itNumber",
          "62",
          "text"
        ],
        [
          "spaceGroup.nameHM",
          "P n m a",
          "text"
        ],
        [
          "spaceGroup.coordSystemCode",
          "abc",
          "text"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_cosio-d20_scan-324f/project:experiment_type:d20",
      "path": "docs/user/cli/pd-neut-cwl_cosio-d20_scan-324f/project",
      "page": "experiment",
      "tier": "basic",
      "group": "experiment_type",
      "selection": "d20",
      "fields": [
        [
          "experimentType.sampleForm",
          "powder",
          "disabled"
        ],
        [
          "experimentType.beamMode",
          "constant wavelength",
          "disabled"
        ],
        [
          "experimentType.radiationProbe",
          "neutron",
          "disabled"
        ],
        [
          "experimentType.scatteringType",
          "bragg",
          "disabled"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_cosio-d20_scan-324f/project:data:d20",
      "path": "docs/user/cli/pd-neut-cwl_cosio-d20_scan-324f/project",
      "page": "experiment",
      "tier": "extras",
      "group": "data",
      "selection": "d20",
      "fields": [
        [
          "range.minimum",
          0.0953,
          "number"
        ],
        [
          "range.maximum",
          150.8953,
          "number"
        ],
        [
          "range.step",
          "0.1\u20130.2",
          "readonly"
        ],
        [
          "range.points",
          1507,
          "number"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_cosio-d20_scan-324f/project:sequential_fit",
      "path": "docs/user/cli/pd-neut-cwl_cosio-d20_scan-324f/project",
      "page": "analysis",
      "tier": "extras",
      "group": "sequential_fit",
      "selection": null,
      "fields": [
        [
          "sequentialFit.dataDir",
          "experiments/d20_scan",
          "readonly"
        ],
        [
          "sequentialFit.filePattern",
          "*.dat",
          "readonly"
        ],
        [
          "sequentialFit.reverse",
          "false",
          "readonly"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_cosio-d20_scan-324f/project:engines",
      "path": "docs/user/cli/pd-neut-cwl_cosio-d20_scan-324f/project",
      "page": "analysis",
      "tier": "extras",
      "group": "engines",
      "selection": null,
      "fields": [
        [
          "statusBar.calculator",
          "crysta",
          "label"
        ],
        [
          "statusBar.minimizer",
          "crysta",
          "label"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_lbco-hrpt_start-2/project:space_group:lbco",
      "path": "docs/user/cli/pd-neut-cwl_lbco-hrpt_start-2/project",
      "page": "structure",
      "tier": "basic",
      "group": "space_group",
      "selection": "lbco",
      "fields": [
        [
          "spaceGroup.crystalSystem",
          "cubic",
          "readonly"
        ],
        [
          "spaceGroup.itNumber",
          "221",
          "text"
        ],
        [
          "spaceGroup.nameHM",
          "P m -3 m",
          "text"
        ],
        [
          "spaceGroup.coordSystemCode",
          "1",
          "text"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_lbco-hrpt_start-2/project:experiment_type:hrpt",
      "path": "docs/user/cli/pd-neut-cwl_lbco-hrpt_start-2/project",
      "page": "experiment",
      "tier": "basic",
      "group": "experiment_type",
      "selection": "hrpt",
      "fields": [
        [
          "experimentType.sampleForm",
          "powder",
          "disabled"
        ],
        [
          "experimentType.beamMode",
          "constant wavelength",
          "disabled"
        ],
        [
          "experimentType.radiationProbe",
          "neutron",
          "disabled"
        ],
        [
          "experimentType.scatteringType",
          "bragg",
          "disabled"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_lbco-hrpt_start-2/project:data:hrpt",
      "path": "docs/user/cli/pd-neut-cwl_lbco-hrpt_start-2/project",
      "page": "experiment",
      "tier": "extras",
      "group": "data",
      "selection": "hrpt",
      "fields": [
        [
          "range.minimum",
          10.0,
          "number"
        ],
        [
          "range.maximum",
          164.85,
          "number"
        ],
        [
          "range.step",
          0.049999999999999996,
          "number"
        ],
        [
          "range.points",
          3098,
          "number"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_lbco-hrpt_start-2/project:engines",
      "path": "docs/user/cli/pd-neut-cwl_lbco-hrpt_start-2/project",
      "page": "analysis",
      "tier": "extras",
      "group": "engines",
      "selection": null,
      "fields": [
        [
          "statusBar.calculator",
          "crysta",
          "label"
        ],
        [
          "statusBar.minimizer",
          "crysta",
          "label"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_lbco-hrpt_start-4/project:space_group:lbco",
      "path": "docs/user/cli/pd-neut-cwl_lbco-hrpt_start-4/project",
      "page": "structure",
      "tier": "basic",
      "group": "space_group",
      "selection": "lbco",
      "fields": [
        [
          "spaceGroup.crystalSystem",
          "cubic",
          "readonly"
        ],
        [
          "spaceGroup.itNumber",
          "221",
          "text"
        ],
        [
          "spaceGroup.nameHM",
          "P m -3 m",
          "text"
        ],
        [
          "spaceGroup.coordSystemCode",
          "1",
          "text"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_lbco-hrpt_start-4/project:experiment_type:hrpt",
      "path": "docs/user/cli/pd-neut-cwl_lbco-hrpt_start-4/project",
      "page": "experiment",
      "tier": "basic",
      "group": "experiment_type",
      "selection": "hrpt",
      "fields": [
        [
          "experimentType.sampleForm",
          "powder",
          "disabled"
        ],
        [
          "experimentType.beamMode",
          "constant wavelength",
          "disabled"
        ],
        [
          "experimentType.radiationProbe",
          "neutron",
          "disabled"
        ],
        [
          "experimentType.scatteringType",
          "bragg",
          "disabled"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_lbco-hrpt_start-4/project:data:hrpt",
      "path": "docs/user/cli/pd-neut-cwl_lbco-hrpt_start-4/project",
      "page": "experiment",
      "tier": "extras",
      "group": "data",
      "selection": "hrpt",
      "fields": [
        [
          "range.minimum",
          10.0,
          "number"
        ],
        [
          "range.maximum",
          164.85,
          "number"
        ],
        [
          "range.step",
          0.049999999999999996,
          "number"
        ],
        [
          "range.points",
          3098,
          "number"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_lbco-hrpt_start-4/project:engines",
      "path": "docs/user/cli/pd-neut-cwl_lbco-hrpt_start-4/project",
      "page": "analysis",
      "tier": "extras",
      "group": "engines",
      "selection": null,
      "fields": [
        [
          "statusBar.calculator",
          "crysta",
          "label"
        ],
        [
          "statusBar.minimizer",
          "crysta",
          "label"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ncaf-wish-2bank_start-3/project:space_group:ncaf",
      "path": "docs/user/cli/pd-neut-tof_ncaf-wish-2bank_start-3/project",
      "page": "structure",
      "tier": "basic",
      "group": "space_group",
      "selection": "ncaf",
      "fields": [
        [
          "spaceGroup.crystalSystem",
          "cubic",
          "readonly"
        ],
        [
          "spaceGroup.itNumber",
          "199",
          "text"
        ],
        [
          "spaceGroup.nameHM",
          "I 21 3",
          "text"
        ],
        [
          "spaceGroup.coordSystemCode",
          "1",
          "text"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ncaf-wish-2bank_start-3/project:experiment_type:wish_4_7",
      "path": "docs/user/cli/pd-neut-tof_ncaf-wish-2bank_start-3/project",
      "page": "experiment",
      "tier": "basic",
      "group": "experiment_type",
      "selection": "wish_4_7",
      "fields": [
        [
          "experimentType.sampleForm",
          "powder",
          "disabled"
        ],
        [
          "experimentType.beamMode",
          "time-of-flight",
          "disabled"
        ],
        [
          "experimentType.radiationProbe",
          "neutron",
          "disabled"
        ],
        [
          "experimentType.scatteringType",
          "bragg",
          "disabled"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ncaf-wish-2bank_start-3/project:data:wish_4_7",
      "path": "docs/user/cli/pd-neut-tof_ncaf-wish-2bank_start-3/project",
      "page": "experiment",
      "tier": "extras",
      "group": "data",
      "selection": "wish_4_7",
      "fields": [
        [
          "range.minimum",
          7468.4165,
          "number"
        ],
        [
          "range.maximum",
          109083.4844,
          "number"
        ],
        [
          "range.step",
          "4.96\u201372.3",
          "readonly"
        ],
        [
          "range.points",
          4043,
          "number"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ncaf-wish-2bank_start-3/project:experiment_type:wish_5_6",
      "path": "docs/user/cli/pd-neut-tof_ncaf-wish-2bank_start-3/project",
      "page": "experiment",
      "tier": "basic",
      "group": "experiment_type",
      "selection": "wish_5_6",
      "fields": [
        [
          "experimentType.sampleForm",
          "powder",
          "disabled"
        ],
        [
          "experimentType.beamMode",
          "time-of-flight",
          "disabled"
        ],
        [
          "experimentType.radiationProbe",
          "neutron",
          "disabled"
        ],
        [
          "experimentType.scatteringType",
          "bragg",
          "disabled"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ncaf-wish-2bank_start-3/project:data:wish_5_6",
      "path": "docs/user/cli/pd-neut-tof_ncaf-wish-2bank_start-3/project",
      "page": "experiment",
      "tier": "extras",
      "group": "data",
      "selection": "wish_5_6",
      "fields": [
        [
          "range.minimum",
          7272.2524,
          "number"
        ],
        [
          "range.maximum",
          103417.6719,
          "number"
        ],
        [
          "range.step",
          "4.69\u201366.6",
          "readonly"
        ],
        [
          "range.points",
          4121,
          "number"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ncaf-wish-2bank_start-3/project:engines",
      "path": "docs/user/cli/pd-neut-tof_ncaf-wish-2bank_start-3/project",
      "page": "analysis",
      "tier": "extras",
      "group": "engines",
      "selection": null,
      "fields": [
        [
          "statusBar.calculator",
          "crysta",
          "label"
        ],
        [
          "statusBar.minimizer",
          "crysta",
          "label"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ncaf-wish-3bank_start-5/project:space_group:ncaf",
      "path": "docs/user/cli/pd-neut-tof_ncaf-wish-3bank_start-5/project",
      "page": "structure",
      "tier": "basic",
      "group": "space_group",
      "selection": "ncaf",
      "fields": [
        [
          "spaceGroup.crystalSystem",
          "cubic",
          "readonly"
        ],
        [
          "spaceGroup.itNumber",
          "199",
          "text"
        ],
        [
          "spaceGroup.nameHM",
          "I 21 3",
          "text"
        ],
        [
          "spaceGroup.coordSystemCode",
          "1",
          "text"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ncaf-wish-3bank_start-5/project:experiment_type:wish_2_9",
      "path": "docs/user/cli/pd-neut-tof_ncaf-wish-3bank_start-5/project",
      "page": "experiment",
      "tier": "basic",
      "group": "experiment_type",
      "selection": "wish_2_9",
      "fields": [
        [
          "experimentType.sampleForm",
          "powder",
          "disabled"
        ],
        [
          "experimentType.beamMode",
          "time-of-flight",
          "disabled"
        ],
        [
          "experimentType.radiationProbe",
          "neutron",
          "disabled"
        ],
        [
          "experimentType.scatteringType",
          "bragg",
          "disabled"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ncaf-wish-3bank_start-5/project:data:wish_2_9",
      "path": "docs/user/cli/pd-neut-tof_ncaf-wish-3bank_start-5/project",
      "page": "experiment",
      "tier": "extras",
      "group": "data",
      "selection": "wish_2_9",
      "fields": [
        [
          "range.minimum",
          6075.1914,
          "number"
        ],
        [
          "range.maximum",
          135112.4062,
          "number"
        ],
        [
          "range.step",
          "4.51\u2013200",
          "readonly"
        ],
        [
          "range.points",
          4166,
          "number"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ncaf-wish-3bank_start-5/project:experiment_type:wish_4_7",
      "path": "docs/user/cli/pd-neut-tof_ncaf-wish-3bank_start-5/project",
      "page": "experiment",
      "tier": "basic",
      "group": "experiment_type",
      "selection": "wish_4_7",
      "fields": [
        [
          "experimentType.sampleForm",
          "powder",
          "disabled"
        ],
        [
          "experimentType.beamMode",
          "time-of-flight",
          "disabled"
        ],
        [
          "experimentType.radiationProbe",
          "neutron",
          "disabled"
        ],
        [
          "experimentType.scatteringType",
          "bragg",
          "disabled"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ncaf-wish-3bank_start-5/project:data:wish_4_7",
      "path": "docs/user/cli/pd-neut-tof_ncaf-wish-3bank_start-5/project",
      "page": "experiment",
      "tier": "extras",
      "group": "data",
      "selection": "wish_4_7",
      "fields": [
        [
          "range.minimum",
          7468.4165,
          "number"
        ],
        [
          "range.maximum",
          109083.4844,
          "number"
        ],
        [
          "range.step",
          "4.96\u201372.3",
          "readonly"
        ],
        [
          "range.points",
          4043,
          "number"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ncaf-wish-3bank_start-5/project:experiment_type:wish_5_6",
      "path": "docs/user/cli/pd-neut-tof_ncaf-wish-3bank_start-5/project",
      "page": "experiment",
      "tier": "basic",
      "group": "experiment_type",
      "selection": "wish_5_6",
      "fields": [
        [
          "experimentType.sampleForm",
          "powder",
          "disabled"
        ],
        [
          "experimentType.beamMode",
          "time-of-flight",
          "disabled"
        ],
        [
          "experimentType.radiationProbe",
          "neutron",
          "disabled"
        ],
        [
          "experimentType.scatteringType",
          "bragg",
          "disabled"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ncaf-wish-3bank_start-5/project:data:wish_5_6",
      "path": "docs/user/cli/pd-neut-tof_ncaf-wish-3bank_start-5/project",
      "page": "experiment",
      "tier": "extras",
      "group": "data",
      "selection": "wish_5_6",
      "fields": [
        [
          "range.minimum",
          7305.1274,
          "number"
        ],
        [
          "range.maximum",
          103417.6719,
          "number"
        ],
        [
          "range.step",
          "4.71\u201366.6",
          "readonly"
        ],
        [
          "range.points",
          4114,
          "number"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ncaf-wish-3bank_start-5/project:engines",
      "path": "docs/user/cli/pd-neut-tof_ncaf-wish-3bank_start-5/project",
      "page": "analysis",
      "tier": "extras",
      "group": "engines",
      "selection": null,
      "fields": [
        [
          "statusBar.calculator",
          "crysta",
          "label"
        ],
        [
          "statusBar.minimizer",
          "crysta",
          "label"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-5/project:space_group:ncaf",
      "path": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-5/project",
      "page": "structure",
      "tier": "basic",
      "group": "space_group",
      "selection": "ncaf",
      "fields": [
        [
          "spaceGroup.crystalSystem",
          "cubic",
          "readonly"
        ],
        [
          "spaceGroup.itNumber",
          "199",
          "text"
        ],
        [
          "spaceGroup.nameHM",
          "I 21 3",
          "text"
        ],
        [
          "spaceGroup.coordSystemCode",
          "1",
          "text"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-5/project:experiment_type:wish_1_10",
      "path": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-5/project",
      "page": "experiment",
      "tier": "basic",
      "group": "experiment_type",
      "selection": "wish_1_10",
      "fields": [
        [
          "experimentType.sampleForm",
          "powder",
          "disabled"
        ],
        [
          "experimentType.beamMode",
          "time-of-flight",
          "disabled"
        ],
        [
          "experimentType.radiationProbe",
          "neutron",
          "disabled"
        ],
        [
          "experimentType.scatteringType",
          "bragg",
          "disabled"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-5/project:data:wish_1_10",
      "path": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-5/project",
      "page": "experiment",
      "tier": "extras",
      "group": "data",
      "selection": "wish_1_10",
      "fields": [
        [
          "range.minimum",
          4862.5732,
          "number"
        ],
        [
          "range.maximum",
          256691.6094,
          "number"
        ],
        [
          "range.step",
          "4.58\u20131190",
          "readonly"
        ],
        [
          "range.points",
          4182,
          "number"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-5/project:experiment_type:wish_2_9",
      "path": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-5/project",
      "page": "experiment",
      "tier": "basic",
      "group": "experiment_type",
      "selection": "wish_2_9",
      "fields": [
        [
          "experimentType.sampleForm",
          "powder",
          "disabled"
        ],
        [
          "experimentType.beamMode",
          "time-of-flight",
          "disabled"
        ],
        [
          "experimentType.radiationProbe",
          "neutron",
          "disabled"
        ],
        [
          "experimentType.scatteringType",
          "bragg",
          "disabled"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-5/project:data:wish_2_9",
      "path": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-5/project",
      "page": "experiment",
      "tier": "extras",
      "group": "data",
      "selection": "wish_2_9",
      "fields": [
        [
          "range.minimum",
          6075.1914,
          "number"
        ],
        [
          "range.maximum",
          135112.4062,
          "number"
        ],
        [
          "range.step",
          "4.51\u2013200",
          "readonly"
        ],
        [
          "range.points",
          4166,
          "number"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-5/project:experiment_type:wish_3_8",
      "path": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-5/project",
      "page": "experiment",
      "tier": "basic",
      "group": "experiment_type",
      "selection": "wish_3_8",
      "fields": [
        [
          "experimentType.sampleForm",
          "powder",
          "disabled"
        ],
        [
          "experimentType.beamMode",
          "time-of-flight",
          "disabled"
        ],
        [
          "experimentType.radiationProbe",
          "neutron",
          "disabled"
        ],
        [
          "experimentType.scatteringType",
          "bragg",
          "disabled"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-5/project:data:wish_3_8",
      "path": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-5/project",
      "page": "experiment",
      "tier": "extras",
      "group": "data",
      "selection": "wish_3_8",
      "fields": [
        [
          "range.minimum",
          7549.5366,
          "number"
        ],
        [
          "range.maximum",
          116924.6406,
          "number"
        ],
        [
          "range.step",
          "5.21\u201380.7",
          "readonly"
        ],
        [
          "range.points",
          3970,
          "number"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-5/project:experiment_type:wish_4_7",
      "path": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-5/project",
      "page": "experiment",
      "tier": "basic",
      "group": "experiment_type",
      "selection": "wish_4_7",
      "fields": [
        [
          "experimentType.sampleForm",
          "powder",
          "disabled"
        ],
        [
          "experimentType.beamMode",
          "time-of-flight",
          "disabled"
        ],
        [
          "experimentType.radiationProbe",
          "neutron",
          "disabled"
        ],
        [
          "experimentType.scatteringType",
          "bragg",
          "disabled"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-5/project:data:wish_4_7",
      "path": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-5/project",
      "page": "experiment",
      "tier": "extras",
      "group": "data",
      "selection": "wish_4_7",
      "fields": [
        [
          "range.minimum",
          7468.4165,
          "number"
        ],
        [
          "range.maximum",
          109083.4844,
          "number"
        ],
        [
          "range.step",
          "4.96\u201372.3",
          "readonly"
        ],
        [
          "range.points",
          4043,
          "number"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-5/project:experiment_type:wish_5_6",
      "path": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-5/project",
      "page": "experiment",
      "tier": "basic",
      "group": "experiment_type",
      "selection": "wish_5_6",
      "fields": [
        [
          "experimentType.sampleForm",
          "powder",
          "disabled"
        ],
        [
          "experimentType.beamMode",
          "time-of-flight",
          "disabled"
        ],
        [
          "experimentType.radiationProbe",
          "neutron",
          "disabled"
        ],
        [
          "experimentType.scatteringType",
          "bragg",
          "disabled"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-5/project:data:wish_5_6",
      "path": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-5/project",
      "page": "experiment",
      "tier": "extras",
      "group": "data",
      "selection": "wish_5_6",
      "fields": [
        [
          "range.minimum",
          7305.1274,
          "number"
        ],
        [
          "range.maximum",
          103417.6719,
          "number"
        ],
        [
          "range.step",
          "4.71\u201366.6",
          "readonly"
        ],
        [
          "range.points",
          4114,
          "number"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-5/project:engines",
      "path": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-5/project",
      "page": "analysis",
      "tier": "extras",
      "group": "engines",
      "selection": null,
      "fields": [
        [
          "statusBar.calculator",
          "crysta",
          "label"
        ],
        [
          "statusBar.minimizer",
          "crysta",
          "label"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-fullprof/project:space_group:ncaf",
      "path": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-fullprof/project",
      "page": "structure",
      "tier": "basic",
      "group": "space_group",
      "selection": "ncaf",
      "fields": [
        [
          "spaceGroup.crystalSystem",
          "cubic",
          "readonly"
        ],
        [
          "spaceGroup.itNumber",
          "199",
          "text"
        ],
        [
          "spaceGroup.nameHM",
          "I 21 3",
          "text"
        ],
        [
          "spaceGroup.coordSystemCode",
          "1",
          "text"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-fullprof/project:experiment_type:wish_1_10",
      "path": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-fullprof/project",
      "page": "experiment",
      "tier": "basic",
      "group": "experiment_type",
      "selection": "wish_1_10",
      "fields": [
        [
          "experimentType.sampleForm",
          "powder",
          "disabled"
        ],
        [
          "experimentType.beamMode",
          "time-of-flight",
          "disabled"
        ],
        [
          "experimentType.radiationProbe",
          "neutron",
          "disabled"
        ],
        [
          "experimentType.scatteringType",
          "bragg",
          "disabled"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-fullprof/project:data:wish_1_10",
      "path": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-fullprof/project",
      "page": "experiment",
      "tier": "extras",
      "group": "data",
      "selection": "wish_1_10",
      "fields": [
        [
          "range.minimum",
          4862.5732,
          "number"
        ],
        [
          "range.maximum",
          256691.6094,
          "number"
        ],
        [
          "range.step",
          "4.58\u20131190",
          "readonly"
        ],
        [
          "range.points",
          4182,
          "number"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-fullprof/project:experiment_type:wish_2_9",
      "path": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-fullprof/project",
      "page": "experiment",
      "tier": "basic",
      "group": "experiment_type",
      "selection": "wish_2_9",
      "fields": [
        [
          "experimentType.sampleForm",
          "powder",
          "disabled"
        ],
        [
          "experimentType.beamMode",
          "time-of-flight",
          "disabled"
        ],
        [
          "experimentType.radiationProbe",
          "neutron",
          "disabled"
        ],
        [
          "experimentType.scatteringType",
          "bragg",
          "disabled"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-fullprof/project:data:wish_2_9",
      "path": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-fullprof/project",
      "page": "experiment",
      "tier": "extras",
      "group": "data",
      "selection": "wish_2_9",
      "fields": [
        [
          "range.minimum",
          6075.1914,
          "number"
        ],
        [
          "range.maximum",
          135112.4062,
          "number"
        ],
        [
          "range.step",
          "4.51\u2013200",
          "readonly"
        ],
        [
          "range.points",
          4166,
          "number"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-fullprof/project:experiment_type:wish_3_8",
      "path": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-fullprof/project",
      "page": "experiment",
      "tier": "basic",
      "group": "experiment_type",
      "selection": "wish_3_8",
      "fields": [
        [
          "experimentType.sampleForm",
          "powder",
          "disabled"
        ],
        [
          "experimentType.beamMode",
          "time-of-flight",
          "disabled"
        ],
        [
          "experimentType.radiationProbe",
          "neutron",
          "disabled"
        ],
        [
          "experimentType.scatteringType",
          "bragg",
          "disabled"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-fullprof/project:data:wish_3_8",
      "path": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-fullprof/project",
      "page": "experiment",
      "tier": "extras",
      "group": "data",
      "selection": "wish_3_8",
      "fields": [
        [
          "range.minimum",
          7549.5366,
          "number"
        ],
        [
          "range.maximum",
          116924.6406,
          "number"
        ],
        [
          "range.step",
          "5.21\u201380.7",
          "readonly"
        ],
        [
          "range.points",
          3970,
          "number"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-fullprof/project:experiment_type:wish_4_7",
      "path": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-fullprof/project",
      "page": "experiment",
      "tier": "basic",
      "group": "experiment_type",
      "selection": "wish_4_7",
      "fields": [
        [
          "experimentType.sampleForm",
          "powder",
          "disabled"
        ],
        [
          "experimentType.beamMode",
          "time-of-flight",
          "disabled"
        ],
        [
          "experimentType.radiationProbe",
          "neutron",
          "disabled"
        ],
        [
          "experimentType.scatteringType",
          "bragg",
          "disabled"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-fullprof/project:data:wish_4_7",
      "path": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-fullprof/project",
      "page": "experiment",
      "tier": "extras",
      "group": "data",
      "selection": "wish_4_7",
      "fields": [
        [
          "range.minimum",
          7468.4165,
          "number"
        ],
        [
          "range.maximum",
          109083.4844,
          "number"
        ],
        [
          "range.step",
          "4.96\u201372.3",
          "readonly"
        ],
        [
          "range.points",
          4043,
          "number"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-fullprof/project:experiment_type:wish_5_6",
      "path": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-fullprof/project",
      "page": "experiment",
      "tier": "basic",
      "group": "experiment_type",
      "selection": "wish_5_6",
      "fields": [
        [
          "experimentType.sampleForm",
          "powder",
          "disabled"
        ],
        [
          "experimentType.beamMode",
          "time-of-flight",
          "disabled"
        ],
        [
          "experimentType.radiationProbe",
          "neutron",
          "disabled"
        ],
        [
          "experimentType.scatteringType",
          "bragg",
          "disabled"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-fullprof/project:data:wish_5_6",
      "path": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-fullprof/project",
      "page": "experiment",
      "tier": "extras",
      "group": "data",
      "selection": "wish_5_6",
      "fields": [
        [
          "range.minimum",
          7305.1274,
          "number"
        ],
        [
          "range.maximum",
          103417.6719,
          "number"
        ],
        [
          "range.step",
          "4.71\u201366.6",
          "readonly"
        ],
        [
          "range.points",
          4114,
          "number"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-fullprof/project:engines",
      "path": "docs/user/cli/pd-neut-tof_ncaf-wish-5bank_start-fullprof/project",
      "page": "analysis",
      "tier": "extras",
      "group": "engines",
      "selection": null,
      "fields": [
        [
          "statusBar.calculator",
          "crysta",
          "label"
        ],
        [
          "statusBar.minimizer",
          "crysta",
          "label"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_si-sepd_start-2/project:space_group:si",
      "path": "docs/user/cli/pd-neut-tof_si-sepd_start-2/project",
      "page": "structure",
      "tier": "basic",
      "group": "space_group",
      "selection": "si",
      "fields": [
        [
          "spaceGroup.crystalSystem",
          "cubic",
          "readonly"
        ],
        [
          "spaceGroup.itNumber",
          "227",
          "text"
        ],
        [
          "spaceGroup.nameHM",
          "F d -3 m",
          "text"
        ],
        [
          "spaceGroup.coordSystemCode",
          "2",
          "text"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_si-sepd_start-2/project:experiment_type:sepd",
      "path": "docs/user/cli/pd-neut-tof_si-sepd_start-2/project",
      "page": "experiment",
      "tier": "basic",
      "group": "experiment_type",
      "selection": "sepd",
      "fields": [
        [
          "experimentType.sampleForm",
          "powder",
          "disabled"
        ],
        [
          "experimentType.beamMode",
          "time-of-flight",
          "disabled"
        ],
        [
          "experimentType.radiationProbe",
          "neutron",
          "disabled"
        ],
        [
          "experimentType.scatteringType",
          "bragg",
          "disabled"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_si-sepd_start-2/project:data:sepd",
      "path": "docs/user/cli/pd-neut-tof_si-sepd_start-2/project",
      "page": "experiment",
      "tier": "extras",
      "group": "data",
      "selection": "sepd",
      "fields": [
        [
          "range.minimum",
          2000.0,
          "number"
        ],
        [
          "range.maximum",
          29995.0,
          "number"
        ],
        [
          "range.step",
          5.0,
          "number"
        ],
        [
          "range.points",
          5600,
          "number"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_si-sepd_start-2/project:engines",
      "path": "docs/user/cli/pd-neut-tof_si-sepd_start-2/project",
      "page": "analysis",
      "tier": "extras",
      "group": "engines",
      "selection": null,
      "fields": [
        [
          "statusBar.calculator",
          "crysta",
          "label"
        ],
        [
          "statusBar.minimizer",
          "crysta",
          "label"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_si-sepd_start-5/project:space_group:si",
      "path": "docs/user/cli/pd-neut-tof_si-sepd_start-5/project",
      "page": "structure",
      "tier": "basic",
      "group": "space_group",
      "selection": "si",
      "fields": [
        [
          "spaceGroup.crystalSystem",
          "cubic",
          "readonly"
        ],
        [
          "spaceGroup.itNumber",
          "227",
          "text"
        ],
        [
          "spaceGroup.nameHM",
          "F d -3 m",
          "text"
        ],
        [
          "spaceGroup.coordSystemCode",
          "2",
          "text"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_si-sepd_start-5/project:experiment_type:sepd",
      "path": "docs/user/cli/pd-neut-tof_si-sepd_start-5/project",
      "page": "experiment",
      "tier": "basic",
      "group": "experiment_type",
      "selection": "sepd",
      "fields": [
        [
          "experimentType.sampleForm",
          "powder",
          "disabled"
        ],
        [
          "experimentType.beamMode",
          "time-of-flight",
          "disabled"
        ],
        [
          "experimentType.radiationProbe",
          "neutron",
          "disabled"
        ],
        [
          "experimentType.scatteringType",
          "bragg",
          "disabled"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_si-sepd_start-5/project:data:sepd",
      "path": "docs/user/cli/pd-neut-tof_si-sepd_start-5/project",
      "page": "experiment",
      "tier": "extras",
      "group": "data",
      "selection": "sepd",
      "fields": [
        [
          "range.minimum",
          2000.0,
          "number"
        ],
        [
          "range.maximum",
          29995.0,
          "number"
        ],
        [
          "range.step",
          5.0,
          "number"
        ],
        [
          "range.points",
          5600,
          "number"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_si-sepd_start-5/project:engines",
      "path": "docs/user/cli/pd-neut-tof_si-sepd_start-5/project",
      "page": "analysis",
      "tier": "extras",
      "group": "engines",
      "selection": null,
      "fields": [
        [
          "statusBar.calculator",
          "crysta",
          "label"
        ],
        [
          "statusBar.minimizer",
          "crysta",
          "label"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_diamond-dream_basic/project:space_group:diamond",
      "path": "docs/user/cli/pd-neut-tof_diamond-dream_basic/project",
      "page": "structure",
      "tier": "basic",
      "group": "space_group",
      "selection": "diamond",
      "fields": [
        [
          "spaceGroup.crystalSystem",
          "cubic",
          "readonly"
        ],
        [
          "spaceGroup.itNumber",
          "227",
          "text"
        ],
        [
          "spaceGroup.nameHM",
          "F d -3 m",
          "text"
        ],
        [
          "spaceGroup.coordSystemCode",
          "1",
          "text"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_diamond-dream_basic/project:experiment_type:dream",
      "path": "docs/user/cli/pd-neut-tof_diamond-dream_basic/project",
      "page": "experiment",
      "tier": "basic",
      "group": "experiment_type",
      "selection": "dream",
      "fields": [
        [
          "experimentType.sampleForm",
          "powder",
          "disabled"
        ],
        [
          "experimentType.beamMode",
          "time-of-flight",
          "disabled"
        ],
        [
          "experimentType.radiationProbe",
          "neutron",
          "disabled"
        ],
        [
          "experimentType.scatteringType",
          "bragg",
          "disabled"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_diamond-dream_basic/project:data:dream",
      "path": "docs/user/cli/pd-neut-tof_diamond-dream_basic/project",
      "page": "experiment",
      "tier": "extras",
      "group": "data",
      "selection": "dream",
      "fields": [
        [
          "range.minimum",
          8530.1009,
          "number"
        ],
        [
          "range.maximum",
          66503.6911,
          "number"
        ],
        [
          "range.step",
          29.001295747873936,
          "number"
        ],
        [
          "range.points",
          2000,
          "number"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_diamond-dream_basic/project:engines",
      "path": "docs/user/cli/pd-neut-tof_diamond-dream_basic/project",
      "page": "analysis",
      "tier": "extras",
      "group": "engines",
      "selection": null,
      "fields": [
        [
          "statusBar.calculator",
          "crysta",
          "label"
        ],
        [
          "statusBar.minimizer",
          "crysta",
          "label"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_lab6-echidna_fcj-asymmetry/project:space_group:lab6",
      "path": "docs/user/cli/pd-neut-cwl_lab6-echidna_fcj-asymmetry/project",
      "page": "structure",
      "tier": "basic",
      "group": "space_group",
      "selection": "lab6",
      "fields": [
        [
          "spaceGroup.crystalSystem",
          "cubic",
          "readonly"
        ],
        [
          "spaceGroup.itNumber",
          "221",
          "text"
        ],
        [
          "spaceGroup.nameHM",
          "P m -3 m",
          "text"
        ],
        [
          "spaceGroup.coordSystemCode",
          "1",
          "text"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_lab6-echidna_fcj-asymmetry/project:experiment_type:echidna",
      "path": "docs/user/cli/pd-neut-cwl_lab6-echidna_fcj-asymmetry/project",
      "page": "experiment",
      "tier": "basic",
      "group": "experiment_type",
      "selection": "echidna",
      "fields": [
        [
          "experimentType.sampleForm",
          "powder",
          "disabled"
        ],
        [
          "experimentType.beamMode",
          "constant wavelength",
          "disabled"
        ],
        [
          "experimentType.radiationProbe",
          "neutron",
          "disabled"
        ],
        [
          "experimentType.scatteringType",
          "bragg",
          "disabled"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_lab6-echidna_fcj-asymmetry/project:data:echidna",
      "path": "docs/user/cli/pd-neut-cwl_lab6-echidna_fcj-asymmetry/project",
      "page": "experiment",
      "tier": "extras",
      "group": "data",
      "selection": "echidna",
      "fields": [
        [
          "range.minimum",
          3.86396,
          "number"
        ],
        [
          "range.maximum",
          163.75638,
          "number"
        ],
        [
          "range.step",
          "0.0304\u20130.0772",
          "readonly"
        ],
        [
          "range.points",
          3200,
          "number"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_lab6-echidna_fcj-asymmetry/project:engines",
      "path": "docs/user/cli/pd-neut-cwl_lab6-echidna_fcj-asymmetry/project",
      "page": "analysis",
      "tier": "extras",
      "group": "engines",
      "selection": null,
      "fields": [
        [
          "statusBar.calculator",
          "crysta",
          "label"
        ],
        [
          "statusBar.minimizer",
          "crysta",
          "label"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_pbso4_beba-asymmetry/project:space_group:pbso4",
      "path": "docs/user/cli/pd-neut-cwl_pbso4_beba-asymmetry/project",
      "page": "structure",
      "tier": "basic",
      "group": "space_group",
      "selection": "pbso4",
      "fields": [
        [
          "spaceGroup.crystalSystem",
          "orthorhombic",
          "readonly"
        ],
        [
          "spaceGroup.itNumber",
          "62",
          "text"
        ],
        [
          "spaceGroup.nameHM",
          "P n m a",
          "text"
        ],
        [
          "spaceGroup.coordSystemCode",
          "abc",
          "text"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_pbso4_beba-asymmetry/project:experiment_type:d1a",
      "path": "docs/user/cli/pd-neut-cwl_pbso4_beba-asymmetry/project",
      "page": "experiment",
      "tier": "basic",
      "group": "experiment_type",
      "selection": "d1a",
      "fields": [
        [
          "experimentType.sampleForm",
          "powder",
          "disabled"
        ],
        [
          "experimentType.beamMode",
          "constant wavelength",
          "disabled"
        ],
        [
          "experimentType.radiationProbe",
          "neutron",
          "disabled"
        ],
        [
          "experimentType.scatteringType",
          "bragg",
          "disabled"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_pbso4_beba-asymmetry/project:data:d1a",
      "path": "docs/user/cli/pd-neut-cwl_pbso4_beba-asymmetry/project",
      "page": "experiment",
      "tier": "extras",
      "group": "data",
      "selection": "d1a",
      "fields": [
        [
          "range.minimum",
          10.0,
          "number"
        ],
        [
          "range.maximum",
          155.95,
          "number"
        ],
        [
          "range.step",
          0.049999999999999996,
          "number"
        ],
        [
          "range.points",
          2920,
          "number"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_pbso4_beba-asymmetry/project:engines",
      "path": "docs/user/cli/pd-neut-cwl_pbso4_beba-asymmetry/project",
      "page": "analysis",
      "tier": "extras",
      "group": "engines",
      "selection": null,
      "fields": [
        [
          "statusBar.calculator",
          "crysta",
          "label"
        ],
        [
          "statusBar.minimizer",
          "crysta",
          "label"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_yap-spodi_3k/project:space_group:Al2O3",
      "path": "docs/user/cli/pd-neut-cwl_yap-spodi_3k/project",
      "page": "structure",
      "tier": "basic",
      "group": "space_group",
      "selection": "Al2O3",
      "fields": [
        [
          "spaceGroup.crystalSystem",
          "trigonal",
          "readonly"
        ],
        [
          "spaceGroup.itNumber",
          "167",
          "text"
        ],
        [
          "spaceGroup.nameHM",
          "R -3 c",
          "text"
        ],
        [
          "spaceGroup.coordSystemCode",
          "h",
          "text"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_yap-spodi_3k/project:space_group:YAlO3",
      "path": "docs/user/cli/pd-neut-cwl_yap-spodi_3k/project",
      "page": "structure",
      "tier": "basic",
      "group": "space_group",
      "selection": "YAlO3",
      "fields": [
        [
          "spaceGroup.crystalSystem",
          "orthorhombic",
          "readonly"
        ],
        [
          "spaceGroup.itNumber",
          "62",
          "text"
        ],
        [
          "spaceGroup.nameHM",
          "P b n m",
          "text"
        ],
        [
          "spaceGroup.coordSystemCode",
          "",
          "text"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_yap-spodi_3k/project:experiment_type:spodi",
      "path": "docs/user/cli/pd-neut-cwl_yap-spodi_3k/project",
      "page": "experiment",
      "tier": "basic",
      "group": "experiment_type",
      "selection": "spodi",
      "fields": [
        [
          "experimentType.sampleForm",
          "powder",
          "disabled"
        ],
        [
          "experimentType.beamMode",
          "constant wavelength",
          "disabled"
        ],
        [
          "experimentType.radiationProbe",
          "neutron",
          "disabled"
        ],
        [
          "experimentType.scatteringType",
          "bragg",
          "disabled"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_yap-spodi_3k/project:data:spodi",
      "path": "docs/user/cli/pd-neut-cwl_yap-spodi_3k/project",
      "page": "experiment",
      "tier": "extras",
      "group": "data",
      "selection": "spodi",
      "fields": [
        [
          "range.minimum",
          4.05,
          "number"
        ],
        [
          "range.maximum",
          151.95,
          "number"
        ],
        [
          "range.step",
          0.04999999999999999,
          "number"
        ],
        [
          "range.points",
          2959,
          "number"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_yap-spodi_3k/project:engines",
      "path": "docs/user/cli/pd-neut-cwl_yap-spodi_3k/project",
      "page": "analysis",
      "tier": "extras",
      "group": "engines",
      "selection": null,
      "fields": [
        [
          "statusBar.calculator",
          "crysta",
          "label"
        ],
        [
          "statusBar.minimizer",
          "crysta",
          "label"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_fe_pseudo-voigt/project:space_group:fe",
      "path": "docs/user/cli/pd-neut-tof_fe_pseudo-voigt/project",
      "page": "structure",
      "tier": "basic",
      "group": "space_group",
      "selection": "fe",
      "fields": [
        [
          "spaceGroup.crystalSystem",
          "cubic",
          "readonly"
        ],
        [
          "spaceGroup.itNumber",
          "229",
          "text"
        ],
        [
          "spaceGroup.nameHM",
          "I m -3 m",
          "text"
        ],
        [
          "spaceGroup.coordSystemCode",
          "1",
          "text"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_fe_pseudo-voigt/project:experiment_type:beer",
      "path": "docs/user/cli/pd-neut-tof_fe_pseudo-voigt/project",
      "page": "experiment",
      "tier": "basic",
      "group": "experiment_type",
      "selection": "beer",
      "fields": [
        [
          "experimentType.sampleForm",
          "powder",
          "disabled"
        ],
        [
          "experimentType.beamMode",
          "time-of-flight",
          "disabled"
        ],
        [
          "experimentType.radiationProbe",
          "neutron",
          "disabled"
        ],
        [
          "experimentType.scatteringType",
          "bragg",
          "disabled"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_fe_pseudo-voigt/project:data:beer",
      "path": "docs/user/cli/pd-neut-tof_fe_pseudo-voigt/project",
      "page": "experiment",
      "tier": "extras",
      "group": "data",
      "selection": "beer",
      "fields": [
        [
          "range.minimum",
          40158.2311891045,
          "number"
        ],
        [
          "range.maximum",
          135592.47482202607,
          "number"
        ],
        [
          "range.step",
          31.853886392830965,
          "number"
        ],
        [
          "range.points",
          2997,
          "number"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_fe_pseudo-voigt/project:engines",
      "path": "docs/user/cli/pd-neut-tof_fe_pseudo-voigt/project",
      "page": "analysis",
      "tier": "extras",
      "group": "engines",
      "selection": null,
      "fields": [
        [
          "statusBar.calculator",
          "crysta",
          "label"
        ],
        [
          "statusBar.minimizer",
          "crysta",
          "label"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_cecoal-polaris_chebyshev/project:space_group:cecoal",
      "path": "docs/user/cli/pd-neut-tof_cecoal-polaris_chebyshev/project",
      "page": "structure",
      "tier": "basic",
      "group": "space_group",
      "selection": "cecoal",
      "fields": [
        [
          "spaceGroup.crystalSystem",
          "orthorhombic",
          "readonly"
        ],
        [
          "spaceGroup.itNumber",
          "51",
          "text"
        ],
        [
          "spaceGroup.nameHM",
          "P m m a",
          "text"
        ],
        [
          "spaceGroup.coordSystemCode",
          "",
          "text"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_cecoal-polaris_chebyshev/project:experiment_type:polaris",
      "path": "docs/user/cli/pd-neut-tof_cecoal-polaris_chebyshev/project",
      "page": "experiment",
      "tier": "basic",
      "group": "experiment_type",
      "selection": "polaris",
      "fields": [
        [
          "experimentType.sampleForm",
          "powder",
          "disabled"
        ],
        [
          "experimentType.beamMode",
          "time-of-flight",
          "disabled"
        ],
        [
          "experimentType.radiationProbe",
          "neutron",
          "disabled"
        ],
        [
          "experimentType.scatteringType",
          "bragg",
          "disabled"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_cecoal-polaris_chebyshev/project:data:polaris",
      "path": "docs/user/cli/pd-neut-tof_cecoal-polaris_chebyshev/project",
      "page": "experiment",
      "tier": "extras",
      "group": "data",
      "selection": "polaris",
      "fields": [
        [
          "range.minimum",
          3001.589,
          "number"
        ],
        [
          "range.maximum",
          19004.658,
          "number"
        ],
        [
          "range.step",
          "1.5\u20139.49",
          "readonly"
        ],
        [
          "range.points",
          3693,
          "number"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_cecoal-polaris_chebyshev/project:engines",
      "path": "docs/user/cli/pd-neut-tof_cecoal-polaris_chebyshev/project",
      "page": "analysis",
      "tier": "extras",
      "group": "engines",
      "selection": null,
      "fields": [
        [
          "statusBar.calculator",
          "crysta",
          "label"
        ],
        [
          "statusBar.minimizer",
          "crysta",
          "label"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ceo2-pearl_polynomial/project:space_group:ceo2",
      "path": "docs/user/cli/pd-neut-tof_ceo2-pearl_polynomial/project",
      "page": "structure",
      "tier": "basic",
      "group": "space_group",
      "selection": "ceo2",
      "fields": [
        [
          "spaceGroup.crystalSystem",
          "cubic",
          "readonly"
        ],
        [
          "spaceGroup.itNumber",
          "225",
          "text"
        ],
        [
          "spaceGroup.nameHM",
          "F m -3 m",
          "text"
        ],
        [
          "spaceGroup.coordSystemCode",
          "",
          "text"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ceo2-pearl_polynomial/project:experiment_type:pearl",
      "path": "docs/user/cli/pd-neut-tof_ceo2-pearl_polynomial/project",
      "page": "experiment",
      "tier": "basic",
      "group": "experiment_type",
      "selection": "pearl",
      "fields": [
        [
          "experimentType.sampleForm",
          "powder",
          "disabled"
        ],
        [
          "experimentType.beamMode",
          "time-of-flight",
          "disabled"
        ],
        [
          "experimentType.radiationProbe",
          "neutron",
          "disabled"
        ],
        [
          "experimentType.scatteringType",
          "bragg",
          "disabled"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ceo2-pearl_polynomial/project:data:pearl",
      "path": "docs/user/cli/pd-neut-tof_ceo2-pearl_polynomial/project",
      "page": "experiment",
      "tier": "extras",
      "group": "data",
      "selection": "pearl",
      "fields": [
        [
          "range.minimum",
          1500.25,
          "number"
        ],
        [
          "range.maximum",
          19400.1875,
          "number"
        ],
        [
          "range.step",
          "2\u201319.4",
          "readonly"
        ],
        [
          "range.points",
          2524,
          "number"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ceo2-pearl_polynomial/project:engines",
      "path": "docs/user/cli/pd-neut-tof_ceo2-pearl_polynomial/project",
      "page": "analysis",
      "tier": "extras",
      "group": "engines",
      "selection": null,
      "fields": [
        [
          "statusBar.calculator",
          "crysta",
          "label"
        ],
        [
          "statusBar.minimizer",
          "crysta",
          "label"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_lab6-11b-echidna_tch-fcj/project:space_group:lab6",
      "path": "docs/user/cli/pd-neut-cwl_lab6-11b-echidna_tch-fcj/project",
      "page": "structure",
      "tier": "basic",
      "group": "space_group",
      "selection": "lab6",
      "fields": [
        [
          "spaceGroup.crystalSystem",
          "cubic",
          "readonly"
        ],
        [
          "spaceGroup.itNumber",
          "221",
          "text"
        ],
        [
          "spaceGroup.nameHM",
          "P m -3 m",
          "text"
        ],
        [
          "spaceGroup.coordSystemCode",
          "",
          "text"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_lab6-11b-echidna_tch-fcj/project:experiment_type:echidna",
      "path": "docs/user/cli/pd-neut-cwl_lab6-11b-echidna_tch-fcj/project",
      "page": "experiment",
      "tier": "basic",
      "group": "experiment_type",
      "selection": "echidna",
      "fields": [
        [
          "experimentType.sampleForm",
          "powder",
          "disabled"
        ],
        [
          "experimentType.beamMode",
          "constant wavelength",
          "disabled"
        ],
        [
          "experimentType.radiationProbe",
          "neutron",
          "disabled"
        ],
        [
          "experimentType.scatteringType",
          "bragg",
          "disabled"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_lab6-11b-echidna_tch-fcj/project:data:echidna",
      "path": "docs/user/cli/pd-neut-cwl_lab6-11b-echidna_tch-fcj/project",
      "page": "experiment",
      "tier": "extras",
      "group": "data",
      "selection": "echidna",
      "fields": [
        [
          "range.minimum",
          3.86396,
          "number"
        ],
        [
          "range.maximum",
          163.75638,
          "number"
        ],
        [
          "range.step",
          "0.0304\u20130.0772",
          "readonly"
        ],
        [
          "range.points",
          3200,
          "number"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-cwl_lab6-11b-echidna_tch-fcj/project:engines",
      "path": "docs/user/cli/pd-neut-cwl_lab6-11b-echidna_tch-fcj/project",
      "page": "analysis",
      "tier": "extras",
      "group": "engines",
      "selection": null,
      "fields": [
        [
          "statusBar.calculator",
          "crysta",
          "label"
        ],
        [
          "statusBar.minimizer",
          "crysta",
          "label"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-xray-cwl_lif_single/project:space_group:lif",
      "path": "docs/user/cli/pd-xray-cwl_lif_single/project",
      "page": "structure",
      "tier": "basic",
      "group": "space_group",
      "selection": "lif",
      "fields": [
        [
          "spaceGroup.crystalSystem",
          "cubic",
          "readonly"
        ],
        [
          "spaceGroup.itNumber",
          "225",
          "text"
        ],
        [
          "spaceGroup.nameHM",
          "F m -3 m",
          "text"
        ],
        [
          "spaceGroup.coordSystemCode",
          "1",
          "text"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-xray-cwl_lif_single/project:experiment_type:cu_ka",
      "path": "docs/user/cli/pd-xray-cwl_lif_single/project",
      "page": "experiment",
      "tier": "basic",
      "group": "experiment_type",
      "selection": "cu_ka",
      "fields": [
        [
          "experimentType.sampleForm",
          "powder",
          "disabled"
        ],
        [
          "experimentType.beamMode",
          "constant wavelength",
          "disabled"
        ],
        [
          "experimentType.radiationProbe",
          "xray",
          "disabled"
        ],
        [
          "experimentType.scatteringType",
          "bragg",
          "disabled"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-xray-cwl_lif_single/project:data:cu_ka",
      "path": "docs/user/cli/pd-xray-cwl_lif_single/project",
      "page": "experiment",
      "tier": "extras",
      "group": "data",
      "selection": "cu_ka",
      "fields": [
        [
          "range.minimum",
          10.0,
          "number"
        ],
        [
          "range.maximum",
          160.0,
          "number"
        ],
        [
          "range.step",
          0.025,
          "number"
        ],
        [
          "range.points",
          6001,
          "number"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-xray-cwl_lif_single/project:engines",
      "path": "docs/user/cli/pd-xray-cwl_lif_single/project",
      "page": "analysis",
      "tier": "extras",
      "group": "engines",
      "selection": null,
      "fields": [
        [
          "statusBar.calculator",
          "crysta",
          "label"
        ],
        [
          "statusBar.minimizer",
          "crysta",
          "label"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ferrite-austenite-beer_joint/project:space_group:austenite",
      "path": "docs/user/cli/pd-neut-tof_ferrite-austenite-beer_joint/project",
      "page": "structure",
      "tier": "basic",
      "group": "space_group",
      "selection": "austenite",
      "fields": [
        [
          "spaceGroup.crystalSystem",
          "cubic",
          "readonly"
        ],
        [
          "spaceGroup.itNumber",
          "225",
          "text"
        ],
        [
          "spaceGroup.nameHM",
          "F m -3 m",
          "text"
        ],
        [
          "spaceGroup.coordSystemCode",
          "1",
          "text"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ferrite-austenite-beer_joint/project:space_group:ferrite",
      "path": "docs/user/cli/pd-neut-tof_ferrite-austenite-beer_joint/project",
      "page": "structure",
      "tier": "basic",
      "group": "space_group",
      "selection": "ferrite",
      "fields": [
        [
          "spaceGroup.crystalSystem",
          "cubic",
          "readonly"
        ],
        [
          "spaceGroup.itNumber",
          "229",
          "text"
        ],
        [
          "spaceGroup.nameHM",
          "I m -3 m",
          "text"
        ],
        [
          "spaceGroup.coordSystemCode",
          "1",
          "text"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ferrite-austenite-beer_joint/project:experiment_type:expt_n2",
      "path": "docs/user/cli/pd-neut-tof_ferrite-austenite-beer_joint/project",
      "page": "experiment",
      "tier": "basic",
      "group": "experiment_type",
      "selection": "expt_n2",
      "fields": [
        [
          "experimentType.sampleForm",
          "powder",
          "disabled"
        ],
        [
          "experimentType.beamMode",
          "time-of-flight",
          "disabled"
        ],
        [
          "experimentType.radiationProbe",
          "neutron",
          "disabled"
        ],
        [
          "experimentType.scatteringType",
          "bragg",
          "disabled"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ferrite-austenite-beer_joint/project:data:expt_n2",
      "path": "docs/user/cli/pd-neut-tof_ferrite-austenite-beer_joint/project",
      "page": "experiment",
      "tier": "extras",
      "group": "data",
      "selection": "expt_n2",
      "fields": [
        [
          "range.minimum",
          40094.52341631884,
          "number"
        ],
        [
          "range.maximum",
          135592.47482202607,
          "number"
        ],
        [
          "range.step",
          31.85388639283096,
          "number"
        ],
        [
          "range.points",
          2999,
          "number"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ferrite-austenite-beer_joint/project:experiment_type:expt_s2",
      "path": "docs/user/cli/pd-neut-tof_ferrite-austenite-beer_joint/project",
      "page": "experiment",
      "tier": "basic",
      "group": "experiment_type",
      "selection": "expt_s2",
      "fields": [
        [
          "experimentType.sampleForm",
          "powder",
          "disabled"
        ],
        [
          "experimentType.beamMode",
          "time-of-flight",
          "disabled"
        ],
        [
          "experimentType.radiationProbe",
          "neutron",
          "disabled"
        ],
        [
          "experimentType.scatteringType",
          "bragg",
          "disabled"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ferrite-austenite-beer_joint/project:data:expt_s2",
      "path": "docs/user/cli/pd-neut-tof_ferrite-austenite-beer_joint/project",
      "page": "experiment",
      "tier": "extras",
      "group": "data",
      "selection": "expt_s2",
      "fields": [
        [
          "range.minimum",
          40094.52341631884,
          "number"
        ],
        [
          "range.maximum",
          135592.47482202607,
          "number"
        ],
        [
          "range.step",
          31.85388639283096,
          "number"
        ],
        [
          "range.points",
          2999,
          "number"
        ]
      ]
    },
    {
      "tag": "docs/user/cli/pd-neut-tof_ferrite-austenite-beer_joint/project:engines",
      "path": "docs/user/cli/pd-neut-tof_ferrite-austenite-beer_joint/project",
      "page": "analysis",
      "tier": "extras",
      "group": "engines",
      "selection": null,
      "fields": [
        [
          "statusBar.calculator",
          "crysta",
          "label"
        ],
        [
          "statusBar.minimizer",
          "crysta",
          "label"
        ]
      ]
    },
    {
      "tag": "tests/fixtures/e04_t1/xray-project:space_group:structure",
      "path": "tests/fixtures/e04_t1/xray-project",
      "page": "structure",
      "tier": "basic",
      "group": "space_group",
      "selection": "structure",
      "fields": [
        [
          "spaceGroup.crystalSystem",
          "cubic",
          "readonly"
        ],
        [
          "spaceGroup.itNumber",
          "225",
          "text"
        ],
        [
          "spaceGroup.nameHM",
          "F m -3 m",
          "text"
        ],
        [
          "spaceGroup.coordSystemCode",
          "",
          "text"
        ]
      ]
    },
    {
      "tag": "tests/fixtures/e04_t1/xray-project:experiment_type:experiment",
      "path": "tests/fixtures/e04_t1/xray-project",
      "page": "experiment",
      "tier": "basic",
      "group": "experiment_type",
      "selection": "experiment",
      "fields": [
        [
          "experimentType.sampleForm",
          "powder",
          "disabled"
        ],
        [
          "experimentType.beamMode",
          "constant wavelength",
          "disabled"
        ],
        [
          "experimentType.radiationProbe",
          "xray",
          "disabled"
        ],
        [
          "experimentType.scatteringType",
          "bragg",
          "disabled"
        ]
      ]
    },
    {
      "tag": "tests/fixtures/e04_t1/xray-project:data:experiment",
      "path": "tests/fixtures/e04_t1/xray-project",
      "page": "experiment",
      "tier": "extras",
      "group": "data",
      "selection": "experiment",
      "fields": [
        [
          "range.minimum",
          20.25,
          "number"
        ],
        [
          "range.maximum",
          80.25,
          "number"
        ],
        [
          "range.step",
          30.0,
          "number"
        ],
        [
          "range.points",
          3,
          "number"
        ]
      ]
    },
    {
      "tag": "tests/fixtures/e04_t1/xray-project:engines",
      "path": "tests/fixtures/e04_t1/xray-project",
      "page": "analysis",
      "tier": "extras",
      "group": "engines",
      "selection": null,
      "fields": [
        [
          "statusBar.calculator",
          "crysta",
          "label"
        ],
        [
          "statusBar.minimizer",
          "crysta",
          "label"
        ]
      ]
    },
    {
      "tag": "tests/fixtures/e04_t1/editable-project:space_group:lbco",
      "path": "tests/fixtures/e04_t1/editable-project",
      "page": "structure",
      "tier": "basic",
      "group": "space_group",
      "selection": "lbco",
      "fields": [
        [
          "spaceGroup.crystalSystem",
          "cubic",
          "readonly"
        ],
        [
          "spaceGroup.itNumber",
          "221",
          "text"
        ],
        [
          "spaceGroup.nameHM",
          "P m -3 m",
          "text"
        ],
        [
          "spaceGroup.coordSystemCode",
          "1",
          "text"
        ]
      ]
    },
    {
      "tag": "tests/fixtures/e04_t1/editable-project:experiment_type:hrpt",
      "path": "tests/fixtures/e04_t1/editable-project",
      "page": "experiment",
      "tier": "basic",
      "group": "experiment_type",
      "selection": "hrpt",
      "fields": [
        [
          "experimentType.sampleForm",
          "powder",
          "disabled"
        ],
        [
          "experimentType.beamMode",
          "constant wavelength",
          "disabled"
        ],
        [
          "experimentType.radiationProbe",
          "neutron",
          "disabled"
        ],
        [
          "experimentType.scatteringType",
          "bragg",
          "disabled"
        ]
      ]
    },
    {
      "tag": "tests/fixtures/e04_t1/editable-project:data:hrpt",
      "path": "tests/fixtures/e04_t1/editable-project",
      "page": "experiment",
      "tier": "extras",
      "group": "data",
      "selection": "hrpt",
      "fields": [
        [
          "range.minimum",
          10.0,
          "number"
        ],
        [
          "range.maximum",
          164.85,
          "number"
        ],
        [
          "range.step",
          0.049999999999999996,
          "number"
        ],
        [
          "range.points",
          3098,
          "number"
        ]
      ]
    },
    {
      "tag": "tests/fixtures/e04_t1/editable-project:engines",
      "path": "tests/fixtures/e04_t1/editable-project",
      "page": "analysis",
      "tier": "extras",
      "group": "engines",
      "selection": null,
      "fields": [
        [
          "statusBar.calculator",
          "crysta",
          "label"
        ],
        [
          "statusBar.minimizer",
          "crysta",
          "label"
        ]
      ]
    },
    {
      "tag": "tests/fixtures/e04_t1/warning-project:space_group:structure",
      "path": "tests/fixtures/e04_t1/warning-project",
      "page": "structure",
      "tier": "basic",
      "group": "space_group",
      "selection": "structure",
      "fields": [
        [
          "spaceGroup.crystalSystem",
          "cubic",
          "readonly"
        ],
        [
          "spaceGroup.itNumber",
          "225",
          "text"
        ],
        [
          "spaceGroup.nameHM",
          "F m -3 m",
          "text"
        ],
        [
          "spaceGroup.coordSystemCode",
          "",
          "text"
        ]
      ]
    },
    {
      "tag": "tests/fixtures/e04_t1/warning-project:experiment_type:experiment",
      "path": "tests/fixtures/e04_t1/warning-project",
      "page": "experiment",
      "tier": "basic",
      "group": "experiment_type",
      "selection": "experiment",
      "fields": [
        [
          "experimentType.sampleForm",
          "powder",
          "disabled"
        ],
        [
          "experimentType.beamMode",
          "constant wavelength",
          "disabled"
        ],
        [
          "experimentType.radiationProbe",
          "xray",
          "disabled"
        ],
        [
          "experimentType.scatteringType",
          "bragg",
          "disabled"
        ]
      ]
    },
    {
      "tag": "tests/fixtures/e04_t1/warning-project:data:experiment",
      "path": "tests/fixtures/e04_t1/warning-project",
      "page": "experiment",
      "tier": "extras",
      "group": "data",
      "selection": "experiment",
      "fields": [
        [
          "range.minimum",
          20.25,
          "number"
        ],
        [
          "range.maximum",
          80.25,
          "number"
        ],
        [
          "range.step",
          30.0,
          "number"
        ],
        [
          "range.points",
          3,
          "number"
        ]
      ]
    },
    {
      "tag": "tests/fixtures/e04_t1/warning-project:engines",
      "path": "tests/fixtures/e04_t1/warning-project",
      "page": "analysis",
      "tier": "extras",
      "group": "engines",
      "selection": null,
      "fields": [
        [
          "statusBar.calculator",
          "crysta",
          "label"
        ],
        [
          "statusBar.minimizer",
          "crysta",
          "label"
        ]
      ]
    }
  ]
};
