# SPDX-License-Identifier: BSD-3-Clause
"""Write the web start page's logo files (owner requests, 2026-10-03).

- app/web/logo.svg: the full logo, still, shown when the page has a message instead of the app.
- app/web/logo-dark.svg, app/web/name-dark.svg: the same in the dark colour scheme's ink.
- app/web/mark.svg, app/web/name.svg, app/web/splash.css: the splash, shown while the chosen build
  downloads, compiles and starts: the name (in the full logo's frame, the mark's place left empty)
  under the mark, which turns.

The mark turns as an HTML element, not inside an SVG image: the page's main thread is blocked for
1.5 to 1.9 s while the wasm module starts, and an animation inside an SVG image is drawn by that
thread, so it froze and then jumped; a transform animation on an element is run by the compositor
and keeps its frames (measured with Chrome traces, 2026-10-03).

The full logo as the app's Home page draws it (app/qml/Components/Wordmark.qml): the mark
(app/resources/logo/App.svg) and beside it "easy" over "diffraction" in Baloo 2, every measure
following the mark's diameter by Wordmark.qml's proportions. The words are glyph outlines, so the
page loads no font. In the splash only the mark turns, as EasyDiffractionBeta's loading window
turns it (gui-components Elements/SplashScreen.qml: a RotationAnimation from 0 to 360*6 degrees in
2000 ms, Easing.OutInElastic, looping). CSS keyframes sample Qt's OutInElastic curve (amplitude 1,
period 0.3, the formulas of Qt's qeasingcurve.cpp); a page asking for reduced motion stays still.
The keyframes are linear between samples 10 ms apart, so each frame draws the angle Qt's curve
gives for its own time, as Qt's animation does per frame.

Run it with any Python that has fontTools (edi's environments do not carry it):
    python app/web/make_logo.py
"""

import math
import re
from itertools import starmap
from pathlib import Path

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

APP = Path(__file__).resolve().parents[1]
# The mark's visible diameter in the SVG's units: App.svg's circle spans 1020 of its 1024 units.
D = 1020.0
NAME_X = D * 1.1094
NAME_SIZE = D * 0.4309
LINES = [
    ('Baloo2-Regular.ttf', 'easy', D * 0.3859),
    ('Baloo2-SemiBold.ttf', 'diffraction', D * 0.8198),
]
# The light and dark themes' foreground (gui-components Style/Colors.qml themeForeground).
INK = {'': '#333', '-dark': '#eee'}
SAMPLES = 200  # keyframes over the 2000 ms turn: one per 10 ms
TURN = 360 * 6  # degrees per loop


def _elastic_phase(c: float, a: float, p: float) -> tuple[float, float]:
    if a < abs(c):
        return c, p / 4
    return a, p / (2 * math.pi) * math.asin(c / a)


def out_in_elastic(t: float, a: float = 1.0, p: float = 0.3) -> float:
    """Qt's Easing.OutInElastic (qeasingcurve.cpp easeOutInElastic), by default amplitude 1."""
    if t < 0.5:  # easeOutElastic_helper(2t, 0, 0.5, 1, a, p)
        u, c = 2 * t, 0.5
        if u == 0:
            return 0.0
        amplitude, s = _elastic_phase(c, a, p)
        return amplitude * 2 ** (-10 * u) * math.sin((u - s) * (2 * math.pi) / p) + c
    u, b, c = 2 * t - 1, 0.5, 0.5  # easeInElastic_helper(2t - 1, 0.5, 0.5, 1, a, p)
    if u == 0:
        return b
    if u == 1:
        return b + c
    amplitude, s = _elastic_phase(c, a, p)
    u -= 1
    return -(amplitude * 2 ** (10 * u) * math.sin((u - s) * (2 * math.pi) / p)) + b


def words(font_file: str, text: str, baseline: float) -> tuple[str, float]:
    """The text's glyph outlines as SVG path data, and where its last advance ends."""
    font = TTFont(APP / 'resources/fonts/Baloo_2' / font_file)
    glyphs = font.getGlyphSet()
    cmap = font.getBestCmap()
    scale = NAME_SIZE / font['head'].unitsPerEm
    x = NAME_X
    paths = []
    for char in text:
        name = cmap[ord(char)]
        pen = SVGPathPen(glyphs)
        glyphs[name].draw(TransformPen(pen, (scale, 0, 0, -scale, x, baseline)))
        if pen.getCommands():
            paths.append(pen.getCommands())
        x += glyphs[name].width * scale
    return ' '.join(paths), x


GENERATED = """<!-- Generated by app/web/make_logo.py from app/resources/logo/App.svg and Baloo 2
     (SIL OFL 1.1). Do not edit. -->"""


def svg_file(width: int, content: str) -> str:
    """One SVG file in a frame `width` wide and the mark's diameter high."""
    return f"""<?xml version="1.0" encoding="utf-8"?>
{GENERATED}
<svg viewBox="0 0 {width} {int(D)}" xmlns="http://www.w3.org/2000/svg">
{content}
</svg>
"""


def main() -> None:
    mark = (APP / 'resources/logo/App.svg').read_text()
    defs = re.search(r'<defs>.*?</defs>', mark, re.DOTALL).group(0)
    body = re.search(r'</defs>(.*)</svg>', mark, re.DOTALL).group(1).strip()
    shapes = list(starmap(words, LINES))
    width = math.ceil(max(end for _, end in shapes))
    mark_group = f"""  {defs}
  <g transform="translate(-2, -2)">
  {body}
  </g>"""
    paths = '\n'.join(f'    <path d="{d}"/>' for d, _ in shapes)
    for scheme, ink in INK.items():
        name_group = f'  <g fill="{ink}">\n{paths}\n  </g>'
        (APP / f'web/logo{scheme}.svg').write_text(svg_file(width, mark_group + '\n' + name_group))
        (APP / f'web/name{scheme}.svg').write_text(svg_file(width, name_group))
    (APP / 'web/mark.svg').write_text(svg_file(int(D), mark_group))
    frames = '\n'.join(
        f'  {100 * i / SAMPLES:.1f}% '
        f'{{ transform: rotate({TURN * out_in_elastic(i / SAMPLES):.2f}deg); }}'
        for i in range(SAMPLES + 1)
    )
    # The mark's share of the full logo's width places it over the name's empty place.
    (APP / 'web/splash.css').write_text(f"""/* Generated by app/web/make_logo.py. Do not edit. */
#splash {{ position: relative; }}
#splash .name {{ display: block; width: 100%; }}
#splash .mark {{
  position: absolute; left: 0; top: 0; width: {100 * D / width:.4f}%;
  transform-origin: 50% 50%; will-change: transform; animation: turn 2000ms linear infinite;
}}
@media (prefers-reduced-motion: reduce) {{ #splash .mark {{ animation: none; }} }}
@keyframes turn {{
{frames}
}}
""")


if __name__ == '__main__':
    main()
