"""Author portable baselines from explicitly supplied pre-release Git revisions.

The resulting inventories and bytes are historical regression references, not
correctness values generated by current product code. Never run during a gate.
The shared metadata adapter removes private citations and personal paths as
well as process labels; numerical reference files are not regenerated.
"""

import argparse
import contextlib
import hashlib
import json
import subprocess
import zipfile
from pathlib import Path

from adapt_test_metadata import payload

ROOT = Path(__file__).resolve().parents[3]
HERE = Path(__file__).resolve().parent / 'history'


def git(*args):
    return subprocess.check_output(['git', '-C', str(ROOT), *args])


def inventory(revision, *prefixes):
    return git('ls-tree', '-r', '--name-only', revision, '--', *prefixes).decode().splitlines()


def write_json(name, value):
    (HERE / name).write_text(json.dumps(value, indent=2, sort_keys=True) + '\n')


def archive(name, revision, paths):
    hashes = {}
    with zipfile.ZipFile(HERE / name, 'w', compression=zipfile.ZIP_DEFLATED) as output:
        for path in sorted(paths):
            data = git('show', revision + ':' + path)
            with contextlib.suppress(UnicodeError):
                data = payload(data.decode(), path).encode()
            if path.endswith('.py'):
                data = subprocess.check_output(
                    [
                        str(ROOT / '.pixi/envs/default/bin/ruff'),
                        'format',
                        '--stdin-filename',
                        path,
                        '-',
                    ],
                    input=data,
                )
            output.writestr(path, data)
            hashes[path] = hashlib.sha256(data).hexdigest()
    return hashes


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    for name in ('api', 'native', 'population', 'documentation', 'pages', 'absorption'):
        parser.add_argument('--' + name, required=True)
    args = parser.parse_args()
    HERE.mkdir(exist_ok=True)
    manifest = {}
    paths = [
        p
        for p in inventory(args.api, 'tests/unit', 'tests/integration', 'tests/system')
        if 'c34_t26' in p or 'c34_t27' in p
    ]
    manifest['api'] = archive('api.zip', args.api, paths)
    manifest['native'] = archive('native.zip', args.native, inventory(args.native, 'core/include'))
    paths = inventory(args.population)
    directories = {'.'}
    for path in paths:
        directories.update(str(parent) for parent in Path(path).parents)
    write_json(
        'population.json', sorted(hashlib.sha256(p.encode()).hexdigest() for p in directories)
    )
    write_json(
        'documentation.json', inventory(args.documentation, 'knowledge/verification/fullprof')
    )
    page_paths = inventory(args.pages, 'docs/dev/verification', 'knowledge/verification/fullprof')
    manifest['pages'] = archive('pages.zip', args.pages, page_paths)
    manifest['input'] = archive('input.zip', args.native, inventory(args.native, 'docs/user'))
    manifest['closure'] = {
        path: hashlib.sha256(git('show', args.native + ':' + path)).hexdigest()
        for path in inventory(args.native, 'core', 'lib', 'src', 'include')
    }
    manifest['absorption_closure'] = {
        path: hashlib.sha256(git('show', args.absorption + ':' + path)).hexdigest()
        for path in inventory(args.absorption, 'core', 'lib')
    }
    write_json('manifest.json', manifest)


if __name__ == '__main__':
    main()
